<?php
declare(strict_types=1);

require_once dirname(__DIR__).'/includes/session_security.php';
app_session_start();
header('Cache-Control: no-store, max-age=0');header('Pragma: no-cache');header('Referrer-Policy: no-referrer');
require_once dirname(__DIR__).'/db.php';
require_once dirname(__DIR__).'/csrf_helper.php';
require_once dirname(__DIR__).'/includes/shop_storefront.php';
require_once dirname(__DIR__).'/includes/shop_program_quick_checkout.php';
require_once dirname(__DIR__).'/includes/auth_rate_limit.php';

function quickProgramH(mixed $value):string{return htmlspecialchars((string)$value,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
function quickProgramMoney(int $minor,string $currency):string{return number_format($minor/100,2,',',' ').' '.quickProgramH($currency);}

$productId=(int)($_POST['product_id']??$_GET['product_id']??0);$variantId=(int)($_POST['variant_id']??$_GET['variant_id']??0);
$product=shopStorefrontProductDetail($pdo,$productId);$variant=null;$offer=false;
if($product!==null&&shopProductRequiresAthlete($pdo,$productId))foreach($product['variants']as$candidate)if((int)$candidate['variant_id']===$variantId){$state=clubProgramVariantSaleState($pdo,$variantId);if($state['saleable']){$variant=$candidate;$offer=$state['offer'];}break;}
if($product===null||$variant===null||!is_array($offer)){http_response_code(404);exit('Kroužek není dostupný pro rychlou přihlášku.');}
if(isset($_SESSION['verejny_uzivatel_id'])){header('Location: produkt.php?id='.$productId,true,303);exit;}
$terms=athleteRegistrationCurrentTerms($pdo);$programTerms=clubProgramTermsEffective($pdo,(int)$offer['program_id'],(int)$offer['id']);
if(!clubProgramTermsComplete($programTerms)){http_response_code(409);exit('Kroužek nemá schválené podmínky.');}
$keyName='shop_quick_program_'.$variantId;if(!isset($_SESSION[$keyName])||!is_array($_SESSION[$keyName]))$_SESSION[$keyName]=['idempotency_key'=>bin2hex(random_bytes(16)),'access_token'=>bin2hex(random_bytes(32))];
$errors=[];
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    if(!csrf_verify((string)($_POST['csrf_token']??'')))$errors[]='Formulář vypršel. Obnovte stránku a zkuste to znovu.';
    else try{
        $email=strtolower(trim((string)($_POST['email']??'')));if(!auth_rate_limit_reserve_attempt($pdo,'quick_program_checkout',$email,auth_rate_limit_request_ip()))throw new ShopCheckoutException('Příliš mnoho pokusů. Zkuste přihlášku dokončit později.');
        $keys=$_SESSION[$keyName];$order=shopProgramQuickCheckoutPlace($pdo,$variantId,$_POST,is_array($_POST['term_version']??null)?$_POST['term_version']:[],(string)$keys['idempotency_key'],(string)$keys['access_token'],shopBankSettingsEffective($pdo));
        unset($_SESSION[$keyName]);header('Location: objednavka.php?code='.rawurlencode((string)$order['public_code']).'&access='.rawurlencode((string)$keys['access_token']),true,303);exit;
    }catch(InvalidArgumentException|ShopCheckoutException|ShopProgramQuickCheckoutException|AthleteRegistrationException|PersonSensitiveException $exception){$errors[]=$exception->getMessage();}
    catch(Throwable $exception){error_log('booking/rychla_prihlaska.php: '.get_class($exception));$errors[]='Přihlášku se nepodařilo bezpečně uložit. Zkuste to znovu.';}
}
$value=static fn(string$key,string$default=''):string=>quickProgramH($_POST[$key]??$default);
?>
<!doctype html><html lang="cs"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><title>Rychlá přihláška – <?=quickProgramH($product['public_name'])?></title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"><?php appUiAssets();?></head>
<body class="bg-light"><?php publicShellNav('shop');?><main class="container py-4" style="max-width:980px"><a class="btn btn-sm btn-outline-secondary mb-3" href="produkt.php?id=<?=$productId?>">← Zpět na kroužek</a>
<div class="row g-4"><aside class="col-lg-4"><div class="card border-0 shadow-sm sticky-lg-top" style="top:1rem"><div class="card-body"><div class="small text-uppercase text-primary fw-semibold">Rychlá přihláška a nákup</div><h1 class="h4 mt-1"><?=quickProgramH($product['public_name'])?></h1><div><?=quickProgramH($offer['name'])?></div><div class="small text-muted"><?=quickProgramH($offer['starts_on'].' – '.$offer['ends_on'])?></div><div class="h5 text-primary mt-3"><?=quickProgramMoney((int)$variant['amount_minor'],(string)$variant['currency'])?></div><div class="small">Volná místa: <strong><?=(int)$offer['available_count']?></strong><?php if($offer['capacity']!==null):?> z <?=(int)$offer['capacity']?><?php endif;?></div><hr><p class="small text-muted mb-2">Máte účet? Přihlášení předvyplní evidované osoby.</p><a class="btn btn-outline-primary btn-sm w-100" href="prihlaseni.php?redirect=<?=rawurlencode('produkt.php?id='.$productId)?>">Přihlásit se</a></div></div></aside>
<section class="col-lg-8"><?php foreach($errors as$error):?><div class="alert alert-danger"><?=quickProgramH($error)?></div><?php endforeach;?><form method="post" class="card border-0 shadow-sm" autocomplete="on"><div class="card-body p-4"><?=csrf_field()?><input type="hidden" name="product_id" value="<?=$productId?>"><input type="hidden" name="variant_id" value="<?=$variantId?>"><input type="hidden" name="photo_public" value="0"><input type="hidden" name="photo_internal" value="0"><?php foreach($terms as$purpose=>$term):?><input type="hidden" name="term_version[<?=quickProgramH($purpose)?>]" value="<?=quickProgramH($term['version'])?>"><?php endforeach;?><?php foreach($programTerms as$purpose=>$term):?><input type="hidden" name="program_term_version[<?=quickProgramH($purpose)?>]" value="<?=quickProgramH($term['terms_version'])?>"><?php endforeach;?>
<h2 class="h5">Kontakt rodiče nebo účastníka</h2><div class="row g-3"><div class="col-sm-6"><label class="form-label">Jméno</label><input class="form-control" name="parent_first_name" maxlength="100" value="<?=$value('parent_first_name')?>" autocomplete="given-name" required></div><div class="col-sm-6"><label class="form-label">Příjmení</label><input class="form-control" name="parent_last_name" maxlength="100" value="<?=$value('parent_last_name')?>" autocomplete="family-name" required></div><div class="col-sm-7"><label class="form-label">E-mail</label><input class="form-control" type="email" name="email" maxlength="254" value="<?=$value('email')?>" autocomplete="email" required></div><div class="col-sm-5"><label class="form-label">Telefon</label><input class="form-control" type="tel" name="contact_phone" maxlength="50" value="<?=$value('contact_phone')?>" autocomplete="tel" required></div></div>
<hr class="my-4"><h2 class="h5">Sportovec</h2><div class="row g-3"><div class="col-12"><label class="form-label">Kdo přihlášku podává</label><select class="form-select" name="requested_role" required><option value="guardian" <?=$value('requested_role','guardian')==='guardian'?'selected':''?>>Rodič / zákonný zástupce dítěte</option><option value="self" <?=$value('requested_role')==='self'?'selected':''?>>Dospělý sportovec za sebe</option></select></div><div class="col-sm-6"><label class="form-label">Jméno sportovce</label><input class="form-control" name="jmeno" maxlength="100" value="<?=$value('jmeno')?>" required></div><div class="col-sm-6"><label class="form-label">Příjmení sportovce</label><input class="form-control" name="prijmeni" maxlength="100" value="<?=$value('prijmeni')?>" required></div><div class="col-sm-6"><label class="form-label">Datum narození</label><input class="form-control" id="quick-birth-date" type="date" name="narozeni" min="1900-01-01" max="<?=date('Y-m-d')?>" value="<?=$value('narozeni')?>" required></div><div class="col-sm-6"><label class="form-label">Státní občanství</label><input class="form-control text-uppercase" name="citizenship_country_code" maxlength="2" pattern="[A-Za-z]{2}" value="<?=$value('citizenship_country_code','CZ')?>" required></div><div class="col-12"><div id="quick-age-warning" class="alert alert-warning py-2 mb-0 d-none"><i class="bi bi-exclamation-triangle-fill me-1"></i><span></span><strong> Přihlášení je přesto možné.</strong></div></div>
<div class="col-sm-7"><label class="form-label">Ulice</label><input class="form-control" name="address_street" maxlength="200" value="<?=$value('address_street')?>" autocomplete="address-line1" required></div><div class="col-sm-3"><label class="form-label">Číslo popisné</label><input class="form-control" name="address_house_number" maxlength="20" value="<?=$value('address_house_number')?>" required></div><div class="col-sm-2"><label class="form-label">Orientační</label><input class="form-control" name="address_orientation_number" maxlength="20" value="<?=$value('address_orientation_number')?>"></div><div class="col-sm-8"><label class="form-label">Obec</label><input class="form-control" name="address_city" maxlength="100" value="<?=$value('address_city')?>" autocomplete="address-level2" required></div><div class="col-sm-4"><label class="form-label">PSČ</label><input class="form-control" name="address_postcode" maxlength="10" value="<?=$value('address_postcode')?>" autocomplete="postal-code" required></div>
<div class="col-sm-6"><label class="form-label">Bylo přiděleno české rodné číslo?</label><select class="form-select" name="has_czech_birth_number" required><option value="1" <?=$value('has_czech_birth_number','1')==='1'?'selected':''?>>Ano</option><option value="0" <?=$value('has_czech_birth_number')==='0'?'selected':''?>>Ne, české RČ nebylo přiděleno</option></select></div><div class="col-sm-6"><label class="form-label">České rodné číslo</label><input class="form-control" name="birth_number" maxlength="11" inputmode="numeric" autocomplete="new-password"><div class="form-text">Po chybě se z bezpečnostních důvodů znovu nevyplní.</div></div></div>
<hr class="my-4"><h2 class="h5">Souhlasy a objednávka</h2><div class="border rounded p-3 small mb-3"><strong><?=quickProgramH($terms['member_data_notice']['version'])?> · Informace o evidenci člena</strong><p><?=quickProgramH($terms['member_data_notice']['text'])?></p><label class="form-check"><input class="form-check-input" type="checkbox" name="member_data_notice" value="1" <?=$value('member_data_notice')==='1'?'checked':''?> required> <span class="form-check-label">Potvrzuji, že jsem informaci četl/a.</span></label></div><div class="border rounded p-3 small mb-3"><strong><?=quickProgramH($terms['birth_number_legal_notice']['version'])?> · Informace k rodnému číslu</strong><p><?=quickProgramH($terms['birth_number_legal_notice']['text'])?></p><label class="form-check"><input class="form-check-input" type="checkbox" name="birth_number_legal_notice" value="1" <?=$value('birth_number_legal_notice')==='1'?'checked':''?> required> <span class="form-check-label">Potvrzuji, že jsem informaci četl/a.</span></label></div>
<div class="border border-primary rounded p-3 small"><details open><summary class="fw-semibold">Storno podmínky</summary><p class="mt-2 mb-3"><?=nl2br(quickProgramH($programTerms['program_cancellation']['consent_text_plain']))?></p></details><details><summary class="fw-semibold">Souhlas s účastí</summary><p class="mt-2 mb-3"><?=nl2br(quickProgramH($programTerms['program_consent']['consent_text_plain']))?></p></details><label class="form-check"><input class="form-check-input" type="checkbox" name="program_terms_accepted" value="1" <?=$value('program_terms_accepted')==='1'?'checked':''?> required> <span class="form-check-label">Četl/a jsem podmínky a souhlasím s přihlášením.</span></label></div>
<button class="btn btn-primary btn-lg w-100 mt-4">Objednat a zobrazit platbu</button><p class="small text-muted text-center mt-2 mb-0">Místo rezervujeme hned. E-mail a sportovce zkontrolujeme následně; platbu tím nezdržujeme.</p></div></form></section></div></main><?php publicShellFooter();?>
<script>(()=>{const input=document.getElementById('quick-birth-date');const box=document.getElementById('quick-age-warning');const text=box?.querySelector('span');const from=<?=json_encode($offer['birth_year_from']!==null?(int)$offer['birth_year_from']:null)?>;const to=<?=json_encode($offer['birth_year_to']!==null?(int)$offer['birth_year_to']:null)?>;const update=()=>{if(!input||!box||!text||!input.value||(!from&&!to)){box?.classList.add('d-none');return;}const year=Number(input.value.slice(0,4));const mismatch=(from!==null&&year<from)||(to!==null&&year>to);box.classList.toggle('d-none',!mismatch);text.textContent=mismatch?`Ročník ${year} je mimo doporučené rozpětí${from!==null&&to!==null?` ${from}–${to}`:''}.`:'';};input?.addEventListener('change',update);update();})();</script></body></html>
