<?php
declare(strict_types=1);
require_once __DIR__.'/includes/init.php';require_once __DIR__.'/includes/individual_lesson_context.php';
if(!isset($_SESSION['trener_id'])){header('Location: login.php');exit;}staffRequireActivePosition('program_coordinator');
function bsah(mixed$value):string{return htmlspecialchars((string)$value,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
$context=individualLessonContextCondition($pdo,'l',INDIVIDUAL_LESSON_CONTEXT_LESSON);$today=(new DateTimeImmutable('today'))->format('Y-m-d');
$statement=$pdo->prepare("SELECT l.id,l.nazev,l.datum,l.cas_od,l.cas_do,l.slot_delka_min,l.cena_kc,l.max_osob,l.typ,l.stav,s.nazev AS venue_name,t.jmeno AS trainer_name,COUNT(r.id) AS reservations,SUM(CASE WHEN r.stav='potvrzena' THEN 1 ELSE 0 END) AS confirmed,SUM(CASE WHEN r.stav='cekaci_listina' THEN 1 ELSE 0 END) AS waiting FROM individualni_lekce l JOIN sportovist s ON s.id=l.sportoviste_id JOIN treneri t ON t.id=l.trener_id LEFT JOIN verejne_rezervace r ON r.lekce_id=l.id WHERE ".$context." AND l.datum>=? GROUP BY l.id ORDER BY l.datum,l.cas_od,l.id LIMIT 300");$statement->execute([$today]);$windows=$statement->fetchAll(PDO::FETCH_ASSOC);
?>
<!doctype html><html lang="cs"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Kurzy a rezervační okna</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"></head><body class="bg-light"><?php require __DIR__.'/hlavicka.php';?><main class="container py-4" style="max-width:1250px"><div class="d-flex flex-wrap justify-content-between gap-2 mb-4"><div><h1 class="h3 mb-1">Kurzy a rezervační okna</h1><p class="text-muted mb-0">Jedno místo pro volbu správného typu nabídky a kontrolu budoucích časových oken.</p></div><a class="btn btn-outline-secondary align-self-start" href="pracovni_pozice.php">Rozcestník programů</a></div>
<div class="row g-3 mb-4"><div class="col-md-6"><section class="card h-100 border-primary"><div class="card-body"><span class="badge text-bg-primary mb-2">Dlouhodobý program</span><h2 class="h5">Kroužek se členstvím</h2><p>Má období, věkové omezení, souhlas, kapacitu, nákup pro konkrétní dítě a po zaplacení zařazení na soupisku.</p><a class="btn btn-primary" href="club_program_wizard_admin.php">Vypsat kroužek</a></div></section></div><div class="col-md-6"><section class="card h-100 border-success"><div class="card-body"><span class="badge text-bg-success mb-2">Rezervovatelná služba</span><h2 class="h5">Kurz, lekce nebo otevřený termín</h2><p>Má datum, okno, délku slotu, cenu, kapacitu, přímé či schvalované přihlášení a čekací listinu.</p><div class="d-flex gap-2"><a class="btn btn-success" href="individualni_lekce_form.php">Vytvořit okna</a><a class="btn btn-outline-success" href="individualni_lekce_sprava.php?vse=1">Spravovat rezervace</a></div></div></section></div></div>
<div class="alert alert-info"><strong>Rozhodovací pravidlo:</strong> pokud účast zakládá dlouhodobé členství a tréninkové zápisy, použijte kroužek. Pokud si zákazník vybírá konkrétní čas, použijte rezervační okno. Běžné oblečení zůstává v katalogu e-shopu.</div>
<section class="card border-0 shadow-sm"><div class="card-header bg-white d-flex justify-content-between"><strong>Budoucí rezervační okna</strong><span class="text-muted"><?=count($windows)?> záznamů</span></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Služba</th><th>Termín a okno</th><th>Cena / kapacita</th><th>Rezervace</th><th>Správce</th></tr></thead><tbody><?php foreach($windows as$window):?><tr><td><strong><?=bsah($window['nazev'])?></strong><div class="small text-muted"><?=bsah($window['venue_name'])?> · <?=bsah($window['typ']==='zelena'?'přímá rezervace':'vyžaduje potvrzení')?></div></td><td><?=bsah($window['datum'])?><div class="small"><?=bsah(substr((string)$window['cas_od'],0,5).'–'.substr((string)$window['cas_do'],0,5).' · '.$window['slot_delka_min'].' min')?></div></td><td><?=number_format((float)$window['cena_kc'],0,',',' ')?> Kč<div class="small text-muted">max. <?=(int)$window['max_osob']?> osob / slot</div></td><td><strong><?=(int)$window['confirmed']?></strong> potvrzeno<div class="small text-muted"><?=(int)$window['waiting']?> čeká na listině</div></td><td><?=bsah($window['trainer_name'])?><div><a class="small" href="individualni_lekce_form.php?edit_id=<?=(int)$window['id']?>">Upravit</a></div></td></tr><?php endforeach;?><?php if($windows===[]):?><tr><td colspan="5" class="text-center text-muted py-4">Nejsou vypsaná žádná budoucí okna.</td></tr><?php endif;?></tbody></table></div></section>
</main></body></html>
