<?php
declare(strict_types=1);

require_once __DIR__.'/includes/init.php';
require_once __DIR__.'/csrf_helper.php';
require_once __DIR__.'/includes/club_program_storefront.php';

if(!isset($_SESSION['trener_id'])||!roleAtLeast('admin')){header('Location: login.php');exit;}
function cpsaH(mixed$value):string{return htmlspecialchars((string)$value,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}

$actorId=(int)$_SESSION['trener_id'];$errors=[];
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    if(!csrf_verify((string)($_POST['csrf_token']??'')))$errors[]='Formulář vypršel. Obnovte stránku.';
    else try{
        $action=(string)($_POST['action']??'');$programId=(int)($_POST['program_id']??0);$reason=(string)($_POST['reason']??'');$confirmed=($_POST['confirmed']??'')==='1';
        if($action==='save_presentation'){$result=clubProgramStorefrontSavePresentation($pdo,$actorId,$programId,$_POST,$reason,$confirmed);$message=$result['changed']?'Veřejné zobrazení bylo uloženo.':'Veřejné zobrazení se nezměnilo.';}
        elseif($action==='add_schedule'){clubProgramStorefrontAddSchedule($pdo,$actorId,$programId,$_POST,$reason,$confirmed);$message='Čas tréninku byl přidán.';}
        elseif($action==='remove_schedule'){$result=clubProgramStorefrontRemoveSchedule($pdo,$actorId,(int)($_POST['slot_id']??0),$reason,$confirmed);$programId=$result['program_id'];$message='Čas tréninku byl odebrán.';}
        elseif($action==='add_image'){
            $upload=$_FILES['program_image']??null;if(!is_array($upload)||(int)($upload['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)throw new InvalidArgumentException('Vyberte JPG nebo PNG obrázek do 5 MB.');
            clubProgramStorefrontAddImage($pdo,$actorId,$programId,(string)$upload['tmp_name'],(string)($_POST['alt_text']??''),(int)($_POST['sort_order']??0),$reason,$confirmed,true,__DIR__);$message='Obrázek kroužku byl uložen.';
        }elseif($action==='remove_image'){$result=clubProgramStorefrontRemoveImage($pdo,$actorId,(int)($_POST['image_id']??0),$reason,$confirmed,__DIR__);$programId=$result['program_id'];$message='Obrázek byl bezpečně odebrán.';}
        else throw new InvalidArgumentException('Neznámá akce rozcestníku.');
        $_SESSION['club_storefront_flash']=$message;header('Location: club_program_storefront_admin.php?id='.$programId,true,303);exit;
    }catch(Throwable$exception){
        if(!($exception instanceof InvalidArgumentException||$exception instanceof ClubProgramStorefrontException||$exception instanceof ShopProductImageException))error_log('club_program_storefront_admin.php: '.$exception->getMessage());
        $errors[]=$exception instanceof InvalidArgumentException||$exception instanceof ClubProgramStorefrontException||$exception instanceof ShopProductImageException?$exception->getMessage():'Změnu rozcestníku se nepodařilo bezpečně uložit.';
    }
}

$success=(string)($_SESSION['club_storefront_flash']??'');unset($_SESSION['club_storefront_flash']);
$programs=$pdo->query("SELECT p.*,pr.public_name,pr.listing_status,pr.sort_order,(SELECT COUNT(*) FROM club_program_offers o WHERE o.program_id=p.id) AS offer_count FROM club_programs p LEFT JOIN club_program_presentations pr ON pr.program_id=p.id WHERE p.status='active' ORDER BY CASE COALESCE(pr.listing_status,'draft') WHEN 'published' THEN 0 WHEN 'draft' THEN 1 ELSE 2 END,COALESCE(pr.sort_order,0),p.name,p.id")->fetchAll(PDO::FETCH_ASSOC);
$selectedId=max(0,(int)($_GET['id']??0));$selected=null;foreach($programs as$program)if((int)$program['id']===$selectedId)$selected=$program;
$presentation=null;$schedules=[];$images=[];$seasons=[];
if($selected!==null){$query=$pdo->prepare('SELECT * FROM club_program_presentations WHERE program_id=?');$query->execute([$selectedId]);$presentation=$query->fetch(PDO::FETCH_ASSOC)?:null;$query=$pdo->prepare('SELECT ss.*,s.name AS season_name FROM club_program_schedule_slots ss JOIN club_seasons s ON s.id=ss.season_id WHERE ss.program_id=? ORDER BY ss.sort_order,ss.weekday,ss.starts_at,ss.id');$query->execute([$selectedId]);$schedules=$query->fetchAll(PDO::FETCH_ASSOC);$query=$pdo->prepare('SELECT * FROM club_program_images WHERE program_id=? ORDER BY sort_order,id');$query->execute([$selectedId]);$images=$query->fetchAll(PDO::FETCH_ASSOC);$seasons=$pdo->query("SELECT id,name,starts_on,ends_on FROM club_seasons WHERE status='active' ORDER BY starts_on DESC,id DESC")->fetchAll(PDO::FETCH_ASSOC);}
?>
<!doctype html><html lang="cs"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Veřejný rozcestník kroužků</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"></head><body class="bg-light"><?php include __DIR__.'/hlavicka.php';?>
<main class="container-fluid py-4" style="max-width:1500px"><div class="d-flex flex-wrap justify-content-between align-items-start gap-2 mb-3"><div><h1 class="h4 mb-1">Veřejný rozcestník kroužků</h1><p class="text-muted mb-0">Název zvířete ani obrázek nejsou povinné. Nehotový program ponechte jako koncept.</p></div><div class="d-flex gap-2"><a class="btn btn-outline-secondary btn-sm" href="club_program_offers_admin.php">Platební varianty</a><a class="btn btn-primary btn-sm" target="_blank" rel="noopener" href="booking/cyklisticke_krouzky.php">Otevřít veřejný náhled</a></div></div>
<?php foreach($errors as$error):?><div class="alert alert-danger"><?=cpsaH($error)?></div><?php endforeach;?><?php if($success!==''):?><div class="alert alert-success"><?=cpsaH($success)?></div><?php endif;?>
<div class="row g-3"><section class="col-xl-4"><div class="card border-0 shadow-sm"><div class="list-group list-group-flush" style="max-height:75vh;overflow:auto"><?php foreach($programs as$program):?><a class="list-group-item list-group-item-action <?=$selectedId===(int)$program['id']?'active':''?>" href="?id=<?=(int)$program['id']?>"><div class="d-flex justify-content-between gap-2"><strong><?=cpsaH($program['public_name']?:$program['name'])?></strong><span class="badge <?=($program['listing_status']??'draft')==='published'?'text-bg-success':'text-bg-secondary'?>"><?=cpsaH($program['listing_status']??'koncept')?></span></div><div class="small"><?=cpsaH($program['code'])?> · <?=(int)$program['offer_count']?> nabídek</div></a><?php endforeach;?></div></div></section>
<section class="col-xl-8"><?php if($selected===null):?><div class="alert alert-secondary">Vyberte program vlevo.</div><?php else:?>
<div class="card border-0 shadow-sm mb-3"><div class="card-header bg-white fw-semibold">Zobrazení programu <?=cpsaH($selected['name'])?></div><div class="card-body"><form method="post" class="row g-3"><?=csrf_field()?><input type="hidden" name="action" value="save_presentation"><input type="hidden" name="program_id" value="<?=$selectedId?>">
<div class="col-md-7"><label class="form-label">Veřejný název</label><input class="form-control" name="public_name" maxlength="160" required value="<?=cpsaH($presentation['public_name']??$selected['name'])?>"><div class="form-text">Může být i popisný, například „Úterý 16:00 · děti 4–6 let“.</div></div><div class="col-md-5"><label class="form-label">Stav</label><select class="form-select" name="listing_status"><option value="draft" <?=($presentation['listing_status']??'draft')==='draft'?'selected':''?>>Koncept – veřejně neviditelný</option><option value="published" <?=($presentation['listing_status']??'')==='published'?'selected':''?>>Zveřejněný</option><option value="hidden" <?=($presentation['listing_status']??'')==='hidden'?'selected':''?>>Skrytý</option></select></div>
<div class="col-12"><label class="form-label">Krátký veřejný popis</label><textarea class="form-control" name="public_summary" maxlength="4000" rows="3"><?=cpsaH($presentation['public_summary']??$selected['description'])?></textarea></div><div class="col-md-5"><label class="form-label">Výchozí místo</label><input class="form-control" name="location_name" maxlength="160" value="<?=cpsaH($presentation['location_name']??'')?>" placeholder="Velodrom Třebešín"></div><div class="col-md-4"><label class="form-label">Věk</label><input class="form-control" name="age_label" maxlength="80" value="<?=cpsaH($presentation['age_label']??'')?>" placeholder="4–6 let"></div><div class="col-md-3"><label class="form-label">Pořadí</label><input class="form-control" type="number" name="sort_order" min="-100000" max="100000" value="<?=cpsaH($presentation['sort_order']??0)?>"></div>
<div class="col-12"><label class="form-check"><input class="form-check-input" type="checkbox" name="interest_enabled" value="1" <?=!isset($presentation['interest_enabled'])||(int)$presentation['interest_enabled']===1?'checked':''?>> Pokud není vhodná nabídka, zobrazit možnost „Nechte nám e-mail“</label></div><div class="col-md-8"><label class="form-label">Důvod změny</label><input class="form-control" name="reason" maxlength="1000" required value="Aktualizace veřejného rozcestníku kroužků."></div><div class="col-md-4"><label class="form-check mb-2"><input class="form-check-input" type="checkbox" name="confirmed" value="1" required> Potvrzuji</label><button class="btn btn-primary w-100">Uložit zobrazení</button></div>
</form></div></div>

<div class="card border-0 shadow-sm mb-3"><div class="card-header bg-white fw-semibold">Pravidelný rozvrh</div><div class="card-body"><form method="post" class="row g-2 align-items-end mb-3"><?=csrf_field()?><input type="hidden" name="action" value="add_schedule"><input type="hidden" name="program_id" value="<?=$selectedId?>"><div class="col-md-4"><label class="form-label">Sezona</label><select class="form-select" name="season_id" required><option value="">Vyberte</option><?php foreach($seasons as$season):?><option value="<?=(int)$season['id']?>"><?=cpsaH($season['name'].' · '.$season['starts_on'].'–'.$season['ends_on'])?></option><?php endforeach;?></select></div><div class="col-md-2"><label class="form-label">Den</label><select class="form-select" name="weekday" required><?php for($day=1;$day<=7;$day++):?><option value="<?=$day?>"><?=cpsaH(clubProgramStorefrontWeekdayLabel($day))?></option><?php endfor;?></select></div><div class="col-md-2"><label class="form-label">Od</label><input class="form-control" type="time" name="starts_at" required></div><div class="col-md-2"><label class="form-label">Do</label><input class="form-control" type="time" name="ends_at" required></div><div class="col-md-2"><label class="form-label">Pořadí</label><input class="form-control" type="number" name="sort_order" value="0"></div><div class="col-md-5"><label class="form-label">Místo <span class="text-muted">(pokud se liší)</span></label><input class="form-control" name="location_name" maxlength="160"></div><div class="col-md-5"><label class="form-label">Důvod</label><input class="form-control" name="reason" maxlength="1000" required value="Doplnění pravidelného času kroužku."></div><div class="col-md-2"><label class="form-check"><input class="form-check-input" type="checkbox" name="confirmed" value="1" required> Potvrzuji</label><button class="btn btn-outline-primary w-100">Přidat</button></div></form>
<?php if($schedules===[]):?><div class="text-muted">Program zatím nemá veřejný rozvrh.</div><?php else:?><div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>Sezona</th><th>Den</th><th>Čas</th><th>Místo</th><th></th></tr></thead><tbody><?php foreach($schedules as$slot):?><tr><td><?=cpsaH($slot['season_name'])?></td><td><?=cpsaH(clubProgramStorefrontWeekdayLabel((int)$slot['weekday']))?></td><td><?=cpsaH(substr((string)$slot['starts_at'],0,5).'–'.substr((string)$slot['ends_at'],0,5))?></td><td><?=cpsaH($slot['location_name']??$presentation['location_name']??'')?></td><td><form method="post" class="d-flex gap-1"><?=csrf_field()?><input type="hidden" name="action" value="remove_schedule"><input type="hidden" name="program_id" value="<?=$selectedId?>"><input type="hidden" name="slot_id" value="<?=(int)$slot['id']?>"><input type="hidden" name="reason" value="Odebrání neaktuálního času."><input type="hidden" name="confirmed" value="1"><button class="btn btn-sm btn-outline-danger">Odebrat</button></form></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></div></div>

<div class="card border-0 shadow-sm"><div class="card-header bg-white fw-semibold">Obrázky kroužku</div><div class="card-body"><form method="post" enctype="multipart/form-data" class="row g-2 align-items-end mb-3"><?=csrf_field()?><input type="hidden" name="action" value="add_image"><input type="hidden" name="program_id" value="<?=$selectedId?>"><div class="col-md-5"><label class="form-label">JPG nebo PNG</label><input class="form-control" type="file" name="program_image" accept="image/jpeg,image/png" required><div class="form-text">Max. 5 MB a 6000 × 6000 px; metadata se odstraní.</div></div><div class="col-md-4"><label class="form-label">Popis obrázku</label><input class="form-control" name="alt_text" maxlength="255" required placeholder="Děti při cyklistickém tréninku"></div><div class="col-md-3"><label class="form-label">Pořadí</label><input class="form-control" type="number" name="sort_order" value="0"></div><div class="col-md-8"><label class="form-label">Důvod</label><input class="form-control" name="reason" maxlength="1000" required value="Doplnění fotografie kroužku."></div><div class="col-md-4"><label class="form-check mb-2"><input class="form-check-input" type="checkbox" name="confirmed" value="1" required> Potvrzuji</label><button class="btn btn-outline-primary w-100">Nahrát obrázek</button></div></form>
<?php if($images===[]):?><div class="text-muted">Bez obrázku se na veřejné stránce použije obecná fotografie kroužků.</div><?php else:?><div class="row g-3"><?php foreach($images as$image):$safe=shopStorefrontSafeImageUrl((string)$image['image_url']);?><div class="col-md-6"><div class="border rounded p-2 h-100"><?php if($safe!==null):?><img class="img-fluid rounded d-block mb-2" src="<?=cpsaH($safe)?>" alt="<?=cpsaH($image['alt_text'])?>" style="height:180px;width:100%;object-fit:cover"><?php endif;?><div class="small mb-2"><?=cpsaH($image['alt_text'])?></div><form method="post" class="d-flex gap-2"><?=csrf_field()?><input type="hidden" name="action" value="remove_image"><input type="hidden" name="program_id" value="<?=$selectedId?>"><input type="hidden" name="image_id" value="<?=(int)$image['id']?>"><input type="hidden" name="reason" value="Odebrání fotografie kroužku."><input type="hidden" name="confirmed" value="1"><button class="btn btn-sm btn-outline-danger">Odebrat</button></form></div></div><?php endforeach;?></div><?php endif;?></div></div>
<?php endif;?></section></div></main></body></html>
