<?php
declare(strict_types=1);

require_once __DIR__.'/includes/init.php';
require_once __DIR__.'/csrf_helper.php';
require_once __DIR__.'/includes/club_program_storefront.php';

if(!isset($_SESSION['trener_id'])||!roleAtLeast('admin')){header('Location: login.php');exit;}

function offerAdminH(mixed$value):string{return htmlspecialchars((string)$value,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
function offerAdminLocalDateTime(mixed$value):string{$value=trim((string)$value);return$value===''?'':str_replace(' ','T',substr($value,0,16));}
function offerAdminMinor(string$value,bool$optional=false):?int
{
    $value=trim(str_replace([' ',chr(194).chr(160),','],['','','.'],$value));
    if($optional&&$value==='')return null;
    if(preg_match('/^[0-9]{1,7}(?:[.][0-9]{1,2})?$/D',$value)!==1)throw new InvalidArgumentException('Cena musí být částka v Kč, například 4100.');
    [$whole,$fraction]=array_pad(explode('.',$value,2),2,'');return((int)$whole*100)+(int)str_pad($fraction,2,'0');
}

$errors=[];$actorId=(int)$_SESSION['trener_id'];
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    if(!csrf_verify((string)($_POST['csrf_token']??'')))$errors[]='Formulář vypršel. Obnovte stránku.';
    else try{
        $action=(string)($_POST['action']??'');$id=(int)($_POST['offer_id']??0);$reason=(string)($_POST['reason']??'');$confirmed=($_POST['confirmed']??'')==='1';
        if($action==='update_offer'){
            $result=clubProgramUpdateOffer($pdo,$actorId,$id,$_POST,$reason,$confirmed);$message=$result['changed']?'Nabídka byla auditovaně upravena.':'Nabídka už měla stejné hodnoty.';
        }elseif($action==='close_offer'){
            $result=clubProgramCloseOffer($pdo,$actorId,$id,$reason,$confirmed);$message=$result['changed']?'Nabídka byla auditovaně uzavřena.':'Nabídka už byla uzavřená.';
        }elseif($action==='add_payment_option'){
            $input=$_POST;$input['amount_minor']=offerAdminMinor((string)($_POST['amount']??''));$input['compare_at_amount_minor']=offerAdminMinor((string)($_POST['compare_at_amount']??''),true);$input['includes_vat']=null;$input['vat_rate_basis_points']=null;
            $created=clubProgramCreatePaymentOption($pdo,$actorId,$id,$input,$reason,$confirmed);$id=(int)$created['offer_id'];$message='Platební varianta byla přidána ke stejnému programu a stejné soupisce.';
        }else throw new InvalidArgumentException('Neznámá akce nabídky.');
        $_SESSION['offer_admin_flash']=$message;header('Location: club_program_offers_admin.php?id='.$id,true,303);exit;
    }catch(Throwable$exception){
        if(!($exception instanceof InvalidArgumentException||$exception instanceof ClubProgramException||$exception instanceof ClubProgramStorefrontException||$exception instanceof ShopManualCatalogException))error_log('club_program_offers_admin.php: '.$exception->getMessage());
        $errors[]=$exception instanceof InvalidArgumentException||$exception instanceof ClubProgramException||$exception instanceof ClubProgramStorefrontException||$exception instanceof ShopManualCatalogException?$exception->getMessage():'Operace selhala bez částečné změny.';
    }
}

$success=(string)($_SESSION['offer_admin_flash']??'');unset($_SESSION['offer_admin_flash']);
$offers=clubProgramAdminOffers($pdo);$selectedId=max(0,(int)($_GET['id']??0));$selected=null;foreach($offers as$offer)if((int)$offer['id']===$selectedId)$selected=$offer;
$events=[];if($selected!==null){$statement=$pdo->prepare("SELECT e.*,t.jmeno AS actor_name FROM club_program_events e LEFT JOIN treneri t ON t.id=e.actor_id AND e.actor_type='trainer' WHERE e.offer_id=? ORDER BY e.id DESC LIMIT 50");$statement->execute([$selectedId]);$events=$statement->fetchAll(PDO::FETCH_ASSOC);foreach($events as&$event){$after=json_decode((string)$event['after_json'],true);$event['reason']=is_array($after)?(string)($after['_audit_reason']??''):'';}unset($event);}
?>
<!doctype html>
<html lang="cs"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Kroužky</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" integrity="sha384-XGjxtQfXaH2tnPFa9x+ruJTuLE3Aa6LhHSWRr1XeTyhezb4abCG4ccI5AkVDxqC+" crossorigin="anonymous"></head>
<body class="bg-light"><?php include __DIR__.'/hlavicka.php';?>
<main class="container-fluid py-4" style="max-width:1550px">
<div class="d-flex justify-content-between mb-3"><div><h1 class="h4 mb-0">Kroužky</h1><div class="small text-muted">Jeden program a jedna soupiska mohou mít více platebních variant: první pololetí, druhé pololetí i zvýhodněný celý rok.</div></div><div class="d-flex gap-2 align-items-start"><a class="btn btn-primary btn-sm" href="club_program_wizard_admin.php">Vypsat nový kroužek</a><a class="btn btn-outline-primary btn-sm" href="club_program_storefront_admin.php">Veřejný rozcestník</a><details><summary class="btn btn-outline-secondary btn-sm">Pokročilé</summary><div class="card card-body position-absolute end-0 mt-2 shadow-sm" style="z-index:10"><a class="btn btn-sm btn-link" href="club_programs_admin.php">Programy a podmínky</a><a class="btn btn-sm btn-link" href="club_program_settings_admin.php">Systémová správa programů</a></div></details></div></div>
<?php foreach($errors as$error):?><div class="alert alert-danger"><?=offerAdminH($error)?></div><?php endforeach;?><?php if($success!==''):?><div class="alert alert-success"><?=offerAdminH($success)?></div><?php endif;?>
<div class="row g-3"><section class="col-xl-7"><div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead><tr><th>Program / období</th><th>Varianta</th><th>Prodej</th><th>Kapacita</th><th>Stav</th><th></th></tr></thead><tbody>
<?php foreach($offers as$offer):?><tr><td><strong><?=offerAdminH($offer['program_name'].' · '.$offer['name'])?></strong><div class="small text-muted"><?=offerAdminH($offer['starts_on'].' – '.$offer['ends_on'].' · '.$offer['sku'])?></div></td><td><span class="badge text-bg-light border"><?=offerAdminH(clubProgramPurchaseOptionLabel((string)($offer['purchase_option']??'custom')))?></span><?php if(!empty($offer['is_featured'])):?><span class="badge text-bg-success ms-1">výhodné</span><?php endif;?></td><td><div class="small"><?=offerAdminH(($offer['sales_open_at']?:'bez začátku').' – '.($offer['sales_close_at']?:'bez konce'))?></div><div class="small <?=$offer['saleable']?'text-success':'text-danger'?>"><?=offerAdminH($offer['sale_reason'])?></div></td><td><?=offerAdminH($offer['available_count']??'∞')?> volných / <?=offerAdminH($offer['capacity']??'∞')?></td><td><span class="badge <?=$offer['status']==='active'?'text-bg-success':($offer['status']==='closed'?'text-bg-secondary':'text-bg-warning')?>"><?=offerAdminH($offer['status'])?></span></td><td><a class="btn btn-sm btn-outline-primary" href="?id=<?=(int)$offer['id']?>">Upravit</a></td></tr><?php endforeach;?>
</tbody></table></div></div></section>
<aside class="col-xl-5"><?php if($selected===null):?><div class="alert alert-secondary">Vyberte nabídku k úpravě.</div><?php else:?>
<div class="card border-0 shadow-sm mb-3"><div class="card-header bg-white fw-semibold">Upravit <?=offerAdminH($selected['name'])?></div><div class="card-body"><div class="alert <?=$selected['saleable']?'alert-success':'alert-warning'?> py-2"><strong>Důvod prodejnosti:</strong> <?=offerAdminH($selected['sale_reason'])?></div>
<form method="post" class="row g-2"><?=csrf_field()?><input type="hidden" name="action" value="update_offer"><input type="hidden" name="offer_id" value="<?=$selectedId?>">
<div class="col-12"><label class="form-label">Název období</label><input class="form-control" name="name" maxlength="180" required value="<?=offerAdminH($selected['name'])?>"></div>
<div class="col-7"><label class="form-label">Platební varianta</label><select class="form-select" name="purchase_option"><?php foreach(['first_half'=>'1. pololetí','second_half'=>'2. pololetí','full_year'=>'Celý rok','custom'=>'Jiná']as$key=>$label):?><option value="<?=$key?>" <?=($selected['purchase_option']??'custom')===$key?'selected':''?>><?=$label?></option><?php endforeach;?></select></div><div class="col-5 d-flex align-items-end"><label class="form-check mb-2"><input class="form-check-input" type="checkbox" name="is_featured" value="1" <?=!empty($selected['is_featured'])?'checked':''?>> Zvýraznit jako výhodnou</label></div>
<div class="col-6"><label class="form-label">Platnost od</label><input class="form-control" type="date" name="starts_on" required value="<?=offerAdminH($selected['starts_on'])?>"></div><div class="col-6"><label class="form-label">Platnost do</label><input class="form-control" type="date" name="ends_on" required value="<?=offerAdminH($selected['ends_on'])?>"></div>
<div class="col-6"><label class="form-label">Prodej od</label><input class="form-control" type="datetime-local" name="sales_open_at" value="<?=offerAdminH(offerAdminLocalDateTime($selected['sales_open_at']))?>"></div><div class="col-6"><label class="form-label">Prodej do</label><input class="form-control" type="datetime-local" name="sales_close_at" value="<?=offerAdminH(offerAdminLocalDateTime($selected['sales_close_at']))?>"></div>
<div class="col-4"><label class="form-label">Kapacita</label><input class="form-control" type="number" min="1" max="100000" name="capacity" value="<?=offerAdminH($selected['capacity'])?>"></div><div class="col-4"><label class="form-label">Ročník od</label><input class="form-control" type="number" min="1900" max="<?=date('Y')?>" name="birth_year_from" value="<?=offerAdminH($selected['birth_year_from'])?>"></div><div class="col-4"><label class="form-label">Ročník do</label><input class="form-control" type="number" min="1900" max="<?=date('Y')?>" name="birth_year_to" value="<?=offerAdminH($selected['birth_year_to'])?>"></div>
<div class="col-5"><label class="form-label">Stav</label><select class="form-select" name="status"><?php foreach(['draft'=>'koncept','active'=>'aktivní','closed'=>'uzavřená']as$key=>$label):?><option value="<?=$key?>" <?=$selected['status']===$key?'selected':''?>><?=$label?></option><?php endforeach;?></select></div><div class="col-7"><label class="form-label">Důvod změny</label><input class="form-control" name="reason" maxlength="1000" required></div><div class="col-12 d-flex justify-content-between"><label class="form-check"><input class="form-check-input" type="checkbox" name="confirmed" value="1" required> Potvrzuji auditovanou změnu</label><button class="btn btn-primary">Uložit nabídku</button></div>
</form></div></div>
<?php if($selected['status']!=='closed'):?>
<div class="card border-primary shadow-sm mb-3"><div class="card-header bg-white fw-semibold">Přidat platební variantu ke stejné skupině</div><div class="card-body"><p class="small text-muted">Nová nabídka použije stejný program, sezonu, produkt a soupisku. Registraci druhého pololetí můžete otevřít okamžitě nastavením „Prodej od“ na dnešek.</p>
<form method="post" class="row g-2"><?=csrf_field()?><input type="hidden" name="action" value="add_payment_option"><input type="hidden" name="offer_id" value="<?=$selectedId?>"><input type="hidden" name="status" value="active">
<div class="col-7"><label class="form-label">Název nabídky</label><input class="form-control" name="name" maxlength="180" required placeholder="Morčata – 2. pololetí 2026/27"></div><div class="col-5"><label class="form-label">Typ</label><select class="form-select" name="purchase_option" required><option value="first_half">1. pololetí</option><option value="second_half">2. pololetí</option><option value="full_year">Celý rok</option><option value="custom">Jiná varianta</option></select></div>
<div class="col-6"><label class="form-label">Kód nabídky</label><input class="form-control" name="code" maxlength="64" required placeholder="MORCATA-2627-H2"></div><div class="col-6"><label class="form-label">SKU</label><input class="form-control" name="sku" maxlength="64" required placeholder="KP-MORCATA-2627-H2"></div>
<div class="col-6"><label class="form-label">Cena v Kč</label><input class="form-control" name="amount" inputmode="decimal" required></div><div class="col-6"><label class="form-label">Běžná cena v Kč <span class="text-muted">(nepovinné)</span></label><input class="form-control" name="compare_at_amount" inputmode="decimal"></div>
<div class="col-6"><label class="form-label">Platnost od</label><input class="form-control" type="date" name="starts_on" required></div><div class="col-6"><label class="form-label">Platnost do</label><input class="form-control" type="date" name="ends_on" required></div>
<div class="col-6"><label class="form-label">Prodej od</label><input class="form-control" type="datetime-local" name="sales_open_at" value="<?=offerAdminH(date('Y-m-d').'T00:00')?>"></div><div class="col-6"><label class="form-label">Prodej do</label><input class="form-control" type="datetime-local" name="sales_close_at"></div>
<div class="col-4"><label class="form-label">Kapacita</label><input class="form-control" type="number" min="1" max="100000" name="capacity" value="<?=offerAdminH($selected['capacity'])?>"></div><div class="col-4"><label class="form-label">Ročník od</label><input class="form-control" type="number" min="1900" max="<?=date('Y')?>" name="birth_year_from" value="<?=offerAdminH($selected['birth_year_from'])?>"></div><div class="col-4"><label class="form-label">Ročník do</label><input class="form-control" type="number" min="1900" max="<?=date('Y')?>" name="birth_year_to" value="<?=offerAdminH($selected['birth_year_to'])?>"></div>
<div class="col-12"><label class="form-check"><input class="form-check-input" type="checkbox" name="is_featured" value="1"> Zvýraznit jako cenově výhodnou variantu</label></div><div class="col-8"><label class="form-label">Důvod</label><input class="form-control" name="reason" maxlength="1000" required value="Přidání další platební varianty stejného kroužku."></div><div class="col-4"><label class="form-check mb-2"><input class="form-check-input" type="checkbox" name="confirmed" value="1" required> Potvrzuji</label><button class="btn btn-primary w-100">Přidat variantu</button></div>
</form></div></div><?php endif;?>
<?php if($selected['status']!=='closed'):?><div class="card border-danger shadow-sm mb-3"><div class="card-body"><form method="post" class="row g-2 align-items-end"><?=csrf_field()?><input type="hidden" name="action" value="close_offer"><input type="hidden" name="offer_id" value="<?=$selectedId?>"><div class="col-8"><label class="form-label">Důvod uzavření prodeje</label><input class="form-control" name="reason" maxlength="1000" required></div><div class="col-4"><label class="form-check mb-2"><input class="form-check-input" type="checkbox" name="confirmed" value="1" required> Potvrzuji</label><button class="btn btn-danger w-100">Uzavřít nabídku</button></div></form></div></div><?php endif;?>
<div class="card border-0 shadow-sm"><div class="card-header bg-white fw-semibold">Audit nabídky</div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Čas</th><th>Akce</th><th>Kdo</th><th>Důvod</th></tr></thead><tbody><?php foreach($events as$event):?><tr><td><?=offerAdminH($event['created_at'])?></td><td><?=offerAdminH($event['action'])?></td><td><?=offerAdminH($event['actor_name']??('#'.$event['actor_id']))?></td><td><?=offerAdminH($event['reason'])?></td></tr><?php endforeach;?></tbody></table></div></div>
<?php endif;?></aside></div></main></body></html>
