<?php
declare(strict_types=1);
require_once __DIR__.'/includes/init.php';require_once __DIR__.'/includes/fio_readonly_import.php';
if(!isset($_SESSION['trener_id'])||!roleAtLeast('admin')){header('Location: login.php');exit;}
function fioAdminH(mixed $value):string{return htmlspecialchars((string)$value,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
function fioAdminMoney(int $minor,string $currency):string{return number_format($minor/100,2,',',' ').' '.fioAdminH($currency);}
$runs=fioAdminRuns($pdo);$movements=fioAdminMovements($pdo);
$labels=['proposed_exact'=>['Přesný návrh','success'],'review_missing_vs'=>['Chybí VS','warning'],'review_unknown_vs'=>['Neznámý VS','warning'],'review_amount'=>['Jiná částka','danger'],'review_currency'=>['Jiná měna','danger'],'review_state'=>['Jiný stav','warning'],'ignored_non_credit'=>['Odchozí / nula','secondary']];
?>
<!doctype html><html lang="cs"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Fio párování K4</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"></head><body class="bg-light"><?php include __DIR__.'/hlavicka.php';?><main class="container-fluid py-4" style="max-width:1450px"><div class="d-flex justify-content-between align-items-center mb-3"><div><h1 class="h4 mb-0">Fio import a návrhy párování K4</h1><div class="small text-muted">Read-only shadow režim: žádný návrh sám nemění platbu ani objednávku.</div></div><a href="pracovni_pozice.php" class="btn btn-outline-secondary btn-sm">Finanční rozcestník</a></div>
<div class="alert alert-info"><strong>Bezpečnostní pojistka:</strong> přesný návrh vyžaduje současně shodný variabilní symbol, částku a měnu a čekající stav objednávky. Potvrzení platby zatím zůstává ruční v přehledu objednávek.</div>
<h2 class="h5 mt-4">Poslední importy</h2><div class="table-responsive"><table class="table table-sm table-striped bg-white"><thead><tr><th>ID</th><th>Období</th><th>Stav</th><th>Načteno</th><th>Nové</th><th>Duplicity</th><th>Návrhy</th><th>Kontrola</th><th>Chyba</th></tr></thead><tbody><?php foreach($runs as $run):?><tr><td><?=(int)$run['id']?></td><td><?=fioAdminH($run['period_from'])?> – <?=fioAdminH($run['period_to'])?></td><td><?=fioAdminH($run['status'])?></td><td><?=(int)$run['fetched_count']?></td><td><?=(int)$run['inserted_count']?></td><td><?=(int)$run['duplicate_count']?></td><td><?=(int)$run['proposed_count']?></td><td><?=(int)$run['review_count']?></td><td><code><?=fioAdminH($run['error_code'])?></code></td></tr><?php endforeach;?><?php if($runs===[]):?><tr><td colspan="9" class="text-muted">Import ještě neběžel.</td></tr><?php endif;?></tbody></table></div>
<h2 class="h5 mt-4">Importované pohyby</h2><div class="table-responsive"><table class="table table-sm table-hover bg-white"><thead><tr><th>Datum</th><th>ID Fio</th><th>Částka</th><th>VS</th><th>Výsledek</th><th>Objednávka</th><th>Vysvětlení</th></tr></thead><tbody><?php foreach($movements as $movement):$label=$labels[$movement['match_status']]??[$movement['match_status'],'secondary'];?><tr><td><?=fioAdminH($movement['booked_on'])?></td><td><code><?=fioAdminH($movement['fio_movement_id'])?></code></td><td><?=fioAdminMoney((int)$movement['amount_minor'],(string)$movement['currency'])?></td><td><?=fioAdminH($movement['variable_symbol']?:'—')?></td><td><span class="badge text-bg-<?=fioAdminH($label[1])?>"><?=fioAdminH($label[0])?></span></td><td><?php if($movement['candidate_order_id']):?><a href="eshop_payments_admin.php?q=<?=rawurlencode((string)($movement['public_code']??''))?>"><?=fioAdminH($movement['public_code']?:'#'.$movement['candidate_order_id'])?></a><?php else:?>—<?php endif;?></td><td><?=fioAdminH($movement['match_reason'])?></td></tr><?php endforeach;?><?php if($movements===[]):?><tr><td colspan="7" class="text-muted">Žádné pohyby.</td></tr><?php endif;?></tbody></table></div></main></body></html>
