<?php
declare(strict_types=1);

require_once __DIR__.'/includes/init.php';
require_once __DIR__.'/csrf_helper.php';
require_once __DIR__.'/includes/shop_member_pricing.php';

if (!isset($_SESSION['trener_id']) || !roleAtLeast('admin')) {header('Location: login.php');exit;}
function memberPriceH(mixed $v):string{return htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
function memberPriceDecimal(string $value):int{
    $value=str_replace([' ', ','],['','.'],trim($value));
    if(preg_match('/^\d{1,9}(?:\.\d{1,2})?$/D',$value)!==1)throw new InvalidArgumentException('Částka musí být nezáporné číslo s nejvýše dvěma desetinnými místy.');
    [$whole,$decimal]=array_pad(explode('.',$value,2),2,'');return (int)$whole*100+(int)str_pad($decimal,2,'0');
}
function memberPricePercent(string $value):int{
    $value=str_replace(',','.',trim($value));if(preg_match('/^\d{1,3}(?:\.\d{1,2})?$/D',$value)!==1)throw new InvalidArgumentException('Procento musí být číslo s nejvýše dvěma desetinnými místy.');
    return (int)round((float)$value*100);
}
$teams=$pdo->query("SELECT t.id,t.name,s.name AS season_name FROM club_teams t JOIN club_seasons s ON s.id=t.season_id WHERE t.status='active' ORDER BY s.starts_on DESC,t.name")->fetchAll(PDO::FETCH_ASSOC);
$errors=[];
if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!csrf_verify((string)($_POST['csrf_token']??'')))$errors[]='Formulář vypršel. Obnovte stránku.';
    else try{
        $action=(string)($_POST['action']??'');$actor=(int)$_SESSION['trener_id'];$note=(string)($_POST['note']??'');
        if(in_array($action,['category','product'],true)&&$teams===[])throw new ShopMemberPricingException('Klubovou cenu nelze založit bez aktivní soupisky. Nejprve požádejte správce členství o založení soupisky.');
        if($action==='category'){
            $type=(string)($_POST['discount_type']??'');$raw=(string)($_POST['value']??'');
            $value=$type==='percentage'?memberPricePercent($raw):memberPriceDecimal($raw);
            shopMemberPricingSetCategoryRule($pdo,(int)($_POST['team_id']??0),(string)($_POST['category_path']??''),$type,$value,$type==='fixed_discount'?'CZK':null,$actor,$note);
        }elseif($action==='product'){
            shopMemberPricingSetProductPrice($pdo,(int)($_POST['team_id']??0),(int)($_POST['product_id']??0),memberPriceDecimal((string)($_POST['amount']??'')),'CZK',$actor,$note);
        }elseif($action==='deactivate')shopMemberPricingDeactivate($pdo,(string)($_POST['kind']??''),(int)($_POST['rule_id']??0),$actor,$note);
        else throw new InvalidArgumentException('Neplatná akce.');
        $_SESSION['flash_member_price']='Klubové cenové pravidlo bylo bezpečně uloženo.';header('Location: eshop_member_prices_admin.php',true,303);exit;
    }catch(PDOException$e){error_log('eshop_member_prices_admin.php: '.$e->getMessage());$errors[]='Databázová operace selhala bez částečné změny.';}catch(InvalidArgumentException|ShopMemberPricingException$e){$errors[]=$e->getMessage();}
}
$success=(string)($_SESSION['flash_member_price']??'');unset($_SESSION['flash_member_price']);
$categories=$pdo->query('SELECT DISTINCT category_path FROM shop_product_categories ORDER BY category_path')->fetchAll(PDO::FETCH_COLUMN);
$products=$pdo->query("SELECT p.id,COALESCE(pub.public_name,p.name) AS name FROM shop_products p LEFT JOIN shop_product_publications pub ON pub.product_id=p.id WHERE p.catalog_status='active' ORDER BY name")->fetchAll(PDO::FETCH_ASSOC);
$categoryRules=$pdo->query('SELECT r.*,t.name AS team_name FROM shop_member_category_rules r JOIN club_teams t ON t.id=r.team_id ORDER BY r.active DESC,t.name,r.category_path')->fetchAll(PDO::FETCH_ASSOC);
$productRules=$pdo->query('SELECT r.*,t.name AS team_name,COALESCE(pub.public_name,p.name) AS product_name FROM shop_member_product_prices r JOIN club_teams t ON t.id=r.team_id JOIN shop_products p ON p.id=r.product_id LEFT JOIN shop_product_publications pub ON pub.product_id=p.id ORDER BY r.active DESC,t.name,product_name')->fetchAll(PDO::FETCH_ASSOC);
$events=$pdo->query('SELECT e.*,t.name AS team_name,tr.jmeno AS actor_name FROM shop_member_price_events e JOIN club_teams t ON t.id=e.team_id JOIN treneri tr ON tr.id=e.actor_trainer_id ORDER BY e.id DESC LIMIT 100')->fetchAll(PDO::FETCH_ASSOC);
$preselected=(int)($_GET['product_id']??0);
?>
<!doctype html><html lang="cs"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Klubové ceny podle soupisek</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"></head><body class="bg-light">
<?php include __DIR__.'/hlavicka.php'; ?><main class="container py-4" style="max-width:1400px"><div class="d-flex justify-content-between gap-2 align-items-center mb-3"><div><h1 class="h4 mb-0">Klubové ceny pro konkrétní soupisky</h1><div class="small text-muted">Tato stránka není určena pro běžnou slevu na zboží. Zvýhodňuje pouze členy vybraných aktivních soupisek.</div></div><a href="eshop_catalog_publication_admin.php" class="btn btn-outline-secondary btn-sm">Produkty</a></div>
<?php foreach($errors as$error):?><div class="alert alert-danger"><?=memberPriceH($error)?></div><?php endforeach;?><?php if($success!==''):?><div class="alert alert-success"><?=memberPriceH($success)?></div><?php endif;?>
<div class="row g-3 mb-3"><div class="col-lg-4"><div class="card h-100 border-primary-subtle"><div class="card-body"><h2 class="h6">Sleva pro všechny zákazníky</h2><p class="small mb-2">U produktu nastavte nižší aktuální cenu a původní cenu. Soupiska se nepoužívá.</p><a class="btn btn-sm btn-outline-primary" href="eshop_produkt_admin.php">Upravit cenu produktu</a></div></div></div><div class="col-lg-4"><div class="card h-100 border-success-subtle"><div class="card-body"><h2 class="h6">Slevový kód</h2><p class="small mb-2">Kupón může platit na zboží, kroužky nebo další služby a zákazník zadá jeho kód.</p><a class="btn btn-sm btn-outline-success" href="eshop_coupons_admin.php">Spravovat kupóny</a></div></div></div><div class="col-lg-4"><div class="card h-100 border-warning-subtle"><div class="card-body"><h2 class="h6">Cena jen pro klubovou skupinu</h2><p class="small mb-0">Použijte formuláře níže. Zákazník musí mít přístup k osobě vedené na vybrané soupisce.</p></div></div></div></div>
<?php if($teams===[]):?><div class="alert alert-warning"><h2 class="h6">Klubové ceny teď nelze založit</h2><p class="mb-2">Není založena žádná aktivní soupiska, proto by nebylo komu klubovou cenu přiřadit. Běžnou slevu pro všechny nastavte přes produkt nebo kupón výše.</p><p class="mb-0">Soupisky zakládá pracovní pozice <strong>Správce členství a soupisek</strong>. Po jejím založení se formuláře automaticky zpřístupní.</p></div><?php endif;?>
<div class="alert alert-info">Přesná cena produktu má v rámci stejné soupisky přednost před slevou kategorie. Pokud má rodina nárok přes více soupisek, systém vybere nejnižší výslednou cenu. Klubová cena nikdy nezvýší veřejnou cenu.</div>
<?php if($teams!==[]):?><div class="row g-3 mb-4"><div class="col-lg-6"><form method="post" class="card border-0 shadow-sm h-100"><div class="card-body"><h2 class="h5">A. Hromadná sleva kategorie</h2><?=csrf_field()?><input type="hidden" name="action" value="category"><label class="form-label">Soupiska</label><select class="form-select mb-2" name="team_id" required><option value="">Vyberte</option><?php foreach($teams as$t):?><option value="<?=(int)$t['id']?>"><?=memberPriceH($t['name'].' · '.$t['season_name'])?></option><?php endforeach;?></select><label class="form-label">Kategorie</label><select class="form-select mb-2" name="category_path" required><option value="">Vyberte</option><?php foreach($categories as$c):?><option><?=memberPriceH($c)?></option><?php endforeach;?></select><div class="row g-2"><div class="col-md-6"><label class="form-label">Druh slevy</label><select class="form-select" name="discount_type"><option value="percentage">Procento</option><option value="fixed_discount">Pevná částka v Kč</option></select></div><div class="col-md-6"><label class="form-label">Hodnota</label><input class="form-control" name="value" inputmode="decimal" placeholder="např. 10 nebo 150" required></div></div><label class="form-label mt-2">Důvod změny</label><input class="form-control" name="note" maxlength="1000" required><button class="btn btn-primary mt-3">Uložit slevu kategorie</button></div></form></div>
<div class="col-lg-6"><form method="post" class="card border-0 shadow-sm h-100"><div class="card-body"><h2 class="h5">B. Přesná cena produktu</h2><?=csrf_field()?><input type="hidden" name="action" value="product"><label class="form-label">Soupiska</label><select class="form-select mb-2" name="team_id" required><option value="">Vyberte</option><?php foreach($teams as$t):?><option value="<?=(int)$t['id']?>"><?=memberPriceH($t['name'].' · '.$t['season_name'])?></option><?php endforeach;?></select><label class="form-label">Produkt</label><select class="form-select mb-2" name="product_id" required><option value="">Vyberte</option><?php foreach($products as$p):?><option value="<?=(int)$p['id']?>" <?=$preselected===(int)$p['id']?'selected':''?>><?=memberPriceH($p['name'])?></option><?php endforeach;?></select><label class="form-label">Klubová cena v Kč</label><input class="form-control" name="amount" inputmode="decimal" placeholder="např. 490" required><div class="form-text">Cena platí pro všechny varianty produktu. Variantní ceny lze doplnit později, pokud je praxe bude vyžadovat.</div><label class="form-label mt-2">Důvod změny</label><input class="form-control" name="note" maxlength="1000" required><button class="btn btn-primary mt-3">Uložit cenu produktu</button></div></form></div></div></div><?php endif;?>
<div class="row g-3"><div class="col-xl-6"><div class="card border-0 shadow-sm"><div class="card-header bg-white fw-semibold">Slevy kategorií</div><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead><tr><th>Soupiska</th><th>Kategorie</th><th>Sleva</th><th></th></tr></thead><tbody><?php foreach($categoryRules as$r):?><tr class="<?=$r['active']?'':'table-secondary'?>"><td><?=memberPriceH($r['team_name'])?></td><td><?=memberPriceH($r['category_path'])?></td><td><?=$r['discount_type']==='percentage'?memberPriceH(number_format((int)$r['value_minor_or_basis_points']/100,2,',','').' %'):memberPriceH(number_format((int)$r['value_minor_or_basis_points']/100,2,',',' ').' Kč')?></td><td><?php if($r['active']):?><form method="post" class="d-flex gap-1"><?=csrf_field()?><input type="hidden" name="action" value="deactivate"><input type="hidden" name="kind" value="category"><input type="hidden" name="rule_id" value="<?=(int)$r['id']?>"><input class="form-control form-control-sm" name="note" required placeholder="Důvod"><button class="btn btn-sm btn-outline-danger">Vypnout</button></form><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></div></div>
<div class="col-xl-6"><div class="card border-0 shadow-sm"><div class="card-header bg-white fw-semibold">Ceny produktů</div><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead><tr><th>Soupiska</th><th>Produkt</th><th>Cena</th><th></th></tr></thead><tbody><?php foreach($productRules as$r):?><tr class="<?=$r['active']?'':'table-secondary'?>"><td><?=memberPriceH($r['team_name'])?></td><td><?=memberPriceH($r['product_name'])?></td><td><?=memberPriceH(number_format((int)$r['amount_minor']/100,2,',',' ').' '.$r['currency'])?></td><td><?php if($r['active']):?><form method="post" class="d-flex gap-1"><?=csrf_field()?><input type="hidden" name="action" value="deactivate"><input type="hidden" name="kind" value="product"><input type="hidden" name="rule_id" value="<?=(int)$r['id']?>"><input class="form-control form-control-sm" name="note" required placeholder="Důvod"><button class="btn btn-sm btn-outline-danger">Vypnout</button></form><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></div></div></div>
<div class="card border-0 shadow-sm mt-3"><div class="card-header bg-white fw-semibold">Poslední změny</div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Čas</th><th>Soupiska</th><th>Typ</th><th>Akce</th><th>Kdo</th><th>Důvod</th></tr></thead><tbody><?php foreach($events as$e):?><tr><td><?=memberPriceH($e['created_at'])?></td><td><?=memberPriceH($e['team_name'])?></td><td><?=memberPriceH($e['rule_type'])?></td><td><?=memberPriceH($e['action'])?></td><td><?=memberPriceH($e['actor_name'])?></td><td><?=memberPriceH($e['note'])?></td></tr><?php endforeach;?></tbody></table></div></div></main></body></html>
