<?php
declare(strict_types=1);

require_once __DIR__ . '/includes/init.php';
require_once __DIR__ . '/csrf_helper.php';
require_once __DIR__ . '/includes/shop_category_admin.php';
if(!isset($_SESSION['trener_id'])||!roleAtLeast('admin')){header('Location: login.php');exit;}

function categoryAdminH(mixed$value):string{return htmlspecialchars((string)$value,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}

$errors=[];$actorId=(int)$_SESSION['trener_id'];
if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!csrf_verify((string)($_POST['csrf_token']??'')))$errors[]='Formulář vypršel. Obnovte stránku.';
    else try{
        $action=(string)($_POST['action']??'');$reason=(string)($_POST['reason']??'');$confirmed=($_POST['confirm_action']??'')==='1';
        if($action==='save_meta'){
            $result=shopCategoryAdminSave($pdo,$actorId,$_POST,$reason,$confirmed);
            $_SESSION['category_admin_flash']='Kategorie byla auditovaně uložena.';
            header('Location: eshop_categories_admin.php?cesta='.rawurlencode($result['category_path']),true,303);exit;
        }
        if($action==='delete_meta'){
            shopCategoryAdminDelete($pdo,$actorId,(string)($_POST['category_path']??''),$reason,$confirmed);
            $_SESSION['category_admin_flash']='Nepoužívaná metadata kategorie byla auditovaně odstraněna.';
            header('Location: eshop_categories_admin.php',true,303);exit;
        }
        if($action==='assign_product'){
            $paths=is_array($_POST['category_paths']??null)?array_values($_POST['category_paths']):[];
            $productId=(int)($_POST['product_id']??0);
            shopCategoryAdminAssignProduct($pdo,$actorId,$productId,$paths,(string)($_POST['default_path']??''),$reason,$confirmed);
            $_SESSION['category_admin_flash']='Kategorie produktu byly auditovaně změněny.';
            header('Location: eshop_categories_admin.php?produkt_id='.$productId,true,303);exit;
        }
        throw new InvalidArgumentException('Neznámá akce správy kategorií.');
    }catch(Throwable$exception){$errors[]=$exception->getMessage();}
}
$success=(string)($_SESSION['category_admin_flash']??'');unset($_SESSION['category_admin_flash']);
$rows=shopCategoryAdminOverview($pdo);$nodes=shopCategoryNodes($pdo);
$selectedPath=trim((string)($_GET['cesta']??''));$selectedMeta=null;
if($selectedPath!=='')try{$selectedPath=shopCategoryPath($selectedPath);$selectedMeta=shopCategoryAdminMeta($pdo,$selectedPath);}catch(InvalidArgumentException$exception){$errors[]=$exception->getMessage();$selectedPath='';}
$formPath=$selectedPath;$formName=(string)($selectedMeta['display_name']??($nodes[$selectedPath]['display_name']??''));
$derivedParent=$selectedPath!==''?shopCategoryDerivedParent($selectedPath):null;
$formParent=$selectedMeta!==null
    ?($selectedMeta['parent_path']===null&&$derivedParent!==null?'__ROOT__':(string)($selectedMeta['parent_path']??''))
    :($selectedPath!==''?(string)($derivedParent??''):'');
$formOrder=(int)($selectedMeta['sort_order']??0);$formVisible=(int)($selectedMeta['visible_in_menu']??1);$formDescription=(string)($selectedMeta['description']??'');
$products=$pdo->query('SELECT p.id,p.name,p.origin,p.catalog_status,COUNT(pc.id) category_count FROM shop_products p LEFT JOIN shop_product_categories pc ON pc.product_id=p.id GROUP BY p.id,p.name,p.origin,p.catalog_status ORDER BY p.name,p.id')->fetchAll(PDO::FETCH_ASSOC);
$productId=max(0,(int)($_GET['produkt_id']??0));if($productId===0&&$products!==[])$productId=(int)$products[0]['id'];
$assigned=[];$defaultPath='';
if($productId>0){$assignedStatement=$pdo->prepare('SELECT category_path,is_default FROM shop_product_categories WHERE product_id=? ORDER BY is_default DESC,sort_order,id');$assignedStatement->execute([$productId]);foreach($assignedStatement->fetchAll(PDO::FETCH_ASSOC)as$row){$assigned[]=(string)$row['category_path'];if((int)$row['is_default']===1)$defaultPath=(string)$row['category_path'];}}
$events=$pdo->query("SELECT e.*,t.jmeno actor_name FROM shop_category_meta_events e LEFT JOIN treneri t ON e.actor_type='trainer' AND t.id=e.actor_id ORDER BY e.id DESC LIMIT 50")->fetchAll(PDO::FETCH_ASSOC);
?>
<!doctype html><html lang="cs"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Kategorie e-shopu</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" integrity="sha384-XGjxtQfXaH2tnPFa9x+ruJTuLE3Aa6LhHSWRr1XeTyhezb4abCG4ccI5AkVDxqC+" crossorigin="anonymous"></head><body class="bg-light"><?php include __DIR__.'/hlavicka.php';?>
<main class="container-fluid py-4" style="max-width:1600px"><div class="d-flex justify-content-between align-items-center flex-wrap gap-2 mb-3"><div><h1 class="h4 mb-0"><i class="bi bi-diagram-3 me-2 text-primary"></i>Kategorie e-shopu</h1><div class="small text-muted">Zobrazované názvy, strom, pořadí a přiřazení produktů. Staré importované cesty fungují i bez metadat.</div></div><div class="d-flex gap-2"><a class="btn btn-outline-primary btn-sm" href="eshop_produkt_admin.php">Produkty</a><a class="btn btn-outline-secondary btn-sm" href="eshop_admin.php">Zpět</a></div></div>
<?php foreach($errors as$error):?><div class="alert alert-danger"><?=categoryAdminH($error)?></div><?php endforeach;?><?php if($success!==''):?><div class="alert alert-success"><?=categoryAdminH($success)?></div><?php endif;?>
<div class="alert alert-info py-2">Cesty typu <code>A &gt; B &gt; C</code> automaticky vytvoří bezpečné virtuální rodiče. Produkt bez kategorie zůstává pod <strong>Vše</strong> a je považován za neúplný katalogový záznam.</div>
<div class="row g-3"><section class="col-xl-7"><div class="card border-0 shadow-sm"><div class="card-header bg-white fw-semibold">Strom kategorií (<?=count($rows)?>)</div><div class="table-responsive"><table class="table table-sm table-hover align-middle mb-0"><thead><tr><th>Kategorie</th><th>Rodič</th><th>Přímo</th><th>Ceny</th><th>Menu</th><th></th></tr></thead><tbody>
<?php foreach($rows as$row):?><tr><td><span class="text-muted"><?=str_repeat('↳ ',(int)$row['depth'])?></span><strong><?=categoryAdminH($row['display_name'])?></strong><div class="small text-muted"><?=categoryAdminH($row['category_path'])?><?php if(!$row['has_metadata']):?> · bez metadat<?php endif;?></div></td><td><?=categoryAdminH($row['parent_path']??'kořen')?></td><td><?=(int)$row['product_count']?></td><td><?=(int)$row['rule_count']?></td><td><?=$row['visible_in_menu']?'<span class="badge text-bg-success">viditelná</span>':'<span class="badge text-bg-secondary">skrytá</span>'?></td><td><a class="btn btn-sm btn-outline-primary" href="eshop_categories_admin.php?cesta=<?=rawurlencode((string)$row['category_path'])?>">Upravit</a></td></tr><?php endforeach;?>
<?php if($rows===[]):?><tr><td colspan="6" class="text-center text-muted py-4">Zatím neexistuje žádná kategorie.</td></tr><?php endif;?></tbody></table></div></div></section>
<aside class="col-xl-5"><div class="card border-0 shadow-sm mb-3"><div class="card-header bg-white fw-semibold"><?=$selectedPath===''?'Nová kategorie':'Metadata kategorie'?></div><div class="card-body"><form method="post" class="row g-2"><?=csrf_field()?><input type="hidden" name="action" value="save_meta"><div class="col-12"><label class="form-label">Technická cesta</label><input class="form-control" name="category_path" maxlength="500" required value="<?=categoryAdminH($formPath)?>" <?=$selectedMeta!==null?'readonly':''?>><div class="form-text">Řetězcová cesta zůstává stabilní kvůli produktům a klubovým cenám.</div></div><div class="col-12"><label class="form-label">Zobrazovaný název</label><input class="form-control" name="display_name" maxlength="255" required value="<?=categoryAdminH($formName)?>"></div><div class="col-md-8"><label class="form-label">Rodič</label><select class="form-select" name="parent_path"><option value="" <?=$formParent===''?'selected':''?>>Odvodit z cesty</option><option value="__ROOT__" <?=$formParent==='__ROOT__'?'selected':''?>>Vynutit kořen</option><?php foreach($rows as$row):if($row['category_path']===$selectedPath)continue;?><option value="<?=categoryAdminH($row['category_path'])?>" <?=$formParent===$row['category_path']?'selected':''?>><?=categoryAdminH(str_repeat('↳ ',(int)$row['depth']).$row['display_name'].' · '.$row['category_path'])?></option><?php endforeach;?></select><div class="form-text">Běžně nechte rodiče odvodit z cesty A &gt; B &gt; C. Volba může hierarchii výslovně přepsat.</div></div><div class="col-md-4"><label class="form-label">Pořadí</label><input class="form-control" type="number" min="-100000" max="100000" name="sort_order" value="<?=$formOrder?>"></div><div class="col-12"><label class="form-label">Popis</label><textarea class="form-control" name="description" maxlength="10000" rows="3"><?=categoryAdminH($formDescription)?></textarea></div><div class="col-12 form-check ms-2"><input class="form-check-input" type="checkbox" name="visible_in_menu" value="1" id="category-visible" <?=$formVisible===1?'checked':''?>><label class="form-check-label" for="category-visible">Viditelná ve veřejném menu, pokud obsahuje prodejný produkt</label></div><div class="col-12"><label class="form-label">Důvod změny</label><textarea class="form-control" name="reason" maxlength="1000" required></textarea></div><div class="col-12 form-check ms-2"><input class="form-check-input" type="checkbox" name="confirm_action" value="1" id="category-confirm" required><label class="form-check-label" for="category-confirm">Potvrzuji auditovanou změnu</label></div><div class="col-12 d-grid"><button class="btn btn-primary">Uložit kategorii</button></div></form>
<?php if($selectedMeta!==null):?><hr><form method="post" onsubmit="return confirm('Opravdu odstranit metadata této nepoužívané kategorie?')"><?=csrf_field()?><input type="hidden" name="action" value="delete_meta"><input type="hidden" name="category_path" value="<?=categoryAdminH($selectedPath)?>"><label class="form-label">Důvod odstranění metadat</label><input class="form-control mb-2" name="reason" minlength="3" maxlength="1000" required><div class="form-check mb-2"><input class="form-check-input" type="checkbox" name="confirm_action" value="1" id="category-delete-confirm" required><label class="form-check-label" for="category-delete-confirm">Potvrzuji odstranění pouze nepoužívaných metadat</label></div><button class="btn btn-outline-danger btn-sm">Odstranit nepoužívaná metadata</button></form><?php endif;?></div></div></aside></div>
<section class="card border-0 shadow-sm mt-3"><div class="card-header bg-white fw-semibold">Přiřazení kategorií produktu</div><div class="card-body"><form method="get" class="row g-2 align-items-end mb-3"><div class="col-lg-9"><label class="form-label">Produkt</label><select class="form-select" name="produkt_id"><?php foreach($products as$product):?><option value="<?=(int)$product['id']?>" <?=$productId===(int)$product['id']?'selected':''?>><?=categoryAdminH($product['name'].' · '.$product['origin'].' · '.$product['catalog_status'].((int)$product['category_count']===0?' · bez kategorie – neúplné':''))?></option><?php endforeach;?></select></div><div class="col-lg-3 d-grid"><button class="btn btn-outline-primary">Načíst přiřazení</button></div></form>
<?php if($productId>0):?><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="assign_product"><input type="hidden" name="product_id" value="<?=$productId?>"><div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>Přiřadit</th><th>Výchozí</th><th>Kategorie</th><th>Cesta</th></tr></thead><tbody><?php foreach($rows as$row):$path=(string)$row['category_path'];?><tr><td><input class="form-check-input" type="checkbox" name="category_paths[]" value="<?=categoryAdminH($path)?>" <?=in_array($path,$assigned,true)?'checked':''?> aria-label="Přiřadit <?=categoryAdminH($path)?>"></td><td><input class="form-check-input" type="radio" name="default_path" value="<?=categoryAdminH($path)?>" <?=$defaultPath===$path?'checked':''?> aria-label="Výchozí <?=categoryAdminH($path)?>"></td><td><?=categoryAdminH(str_repeat('↳ ',(int)$row['depth']).$row['display_name'])?></td><td class="small text-muted"><?=categoryAdminH($path)?></td></tr><?php endforeach;?></tbody></table></div><div class="row g-2"><div class="col-lg-7"><label class="form-label">Důvod změny</label><input class="form-control" name="reason" minlength="3" maxlength="1000" required></div><div class="col-lg-3 d-flex align-items-end"><div class="form-check mb-2"><input class="form-check-input" type="checkbox" name="confirm_action" value="1" id="assign-confirm" required><label class="form-check-label" for="assign-confirm">Potvrzuji změnu</label></div></div><div class="col-lg-2 d-grid align-items-end"><button class="btn btn-primary">Uložit přiřazení</button></div></div><div class="form-text">Necháte-li vše nezaškrtnuté, produkt zůstane pouze pod „Vše“. Při alespoň jedné kategorii musí být právě jedna výchozí.</div></form><?php endif;?></div></section>
<section class="card border-0 shadow-sm mt-3"><div class="card-header bg-white fw-semibold">Poslední auditované změny kategorií</div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Čas</th><th>Cesta</th><th>Akce</th><th>Kdo</th><th>Důvod</th></tr></thead><tbody><?php foreach($events as$event):?><tr><td><?=categoryAdminH($event['created_at'])?></td><td><?=categoryAdminH($event['category_path'])?></td><td><?=categoryAdminH($event['action'])?></td><td><?=categoryAdminH($event['actor_name']??('#'.$event['actor_id']))?></td><td><?=categoryAdminH($event['reason'])?></td></tr><?php endforeach;?><?php if($events===[]):?><tr><td colspan="5" class="text-center text-muted py-3">Zatím bez změn.</td></tr><?php endif;?></tbody></table></div></section></main></body></html>
