<?php
declare(strict_types=1);
require_once __DIR__.'/includes/init.php';require_once __DIR__.'/includes/fio_readonly_import.php';
if(!isset($_SESSION['trener_id'])||!roleAtLeast('admin')){header('Location: login.php');exit;}
function fioAdminH(mixed $value):string{return htmlspecialchars((string)$value,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
function fioAdminMoney(int $minor,string $currency):string{return number_format($minor/100,2,',',' ').' '.fioAdminH($currency);}
$errors=[];$success='';
if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!csrf_verify((string)($_POST['csrf_token']??'')))$errors[]='Formulář vypršel. Obnovte stránku a zkuste to znovu.';
    else try{
        if((string)($_POST['action']??'')!=='confirm_exact')throw new InvalidArgumentException('Neznámá akce.');
        $result=fioAdminConfirmExactMovement($pdo,(int)($_POST['movement_id']??0),(int)$_SESSION['trener_id'],(string)($_POST['reason']??''),isset($_POST['confirmed']));
        $success=$result['changed']?'Bankovní pohyb byl svázán s platbou a platba byla potvrzena.':'Tento pohyb už byl dříve správně potvrzen.';
    }catch(InvalidArgumentException|FioImportException|ShopCheckoutException|MemberChargeAdminException $exception){$errors[]=$exception->getMessage();}
    catch(Throwable){$errors[]='Potvrzení selhalo bez částečného zápisu. Zkuste to znovu nebo kontaktujte správce.';}
}
$runs=fioAdminRuns($pdo);$movements=fioAdminMovements($pdo);
$labels=['proposed_exact'=>['Přesná shoda','success'],'confirmed'=>['Potvrzeno','primary'],'review_missing_vs'=>['Chybí VS','warning'],'review_unknown_vs'=>['Neznámý VS','warning'],'review_amount'=>['Jiná částka','danger'],'review_currency'=>['Jiná měna','danger'],'review_state'=>['Jiný stav','warning'],'review_type'=>['Nepodporovaný typ','warning'],'ignored_non_credit'=>['Odchozí / nula','secondary']];
?>
<!doctype html><html lang="cs"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Fio párování K4</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"></head><body class="bg-light"><?php include __DIR__.'/hlavicka.php';?><main class="container-fluid py-4" style="max-width:1550px"><div class="d-flex justify-content-between align-items-center mb-3"><div><h1 class="h4 mb-0">Fio import a párování plateb K4</h1><div class="small text-muted">Import pouze zapisuje bankovní pohyby a návrhy. Uhrazení nastane až po výslovném potvrzení správce.</div></div><div class="d-flex gap-2"><a href="eshop_bank_admin.php" class="btn btn-outline-primary btn-sm">Nastavení účtu</a><a href="pracovni_pozice.php" class="btn btn-outline-secondary btn-sm">Finanční rozcestník</a></div></div>
<?php foreach($errors as$error):?><div class="alert alert-danger"><?=fioAdminH($error)?></div><?php endforeach;?><?php if($success!==''):?><div class="alert alert-success"><?=fioAdminH($success)?></div><?php endif;?>
<div class="alert alert-info"><strong>Bezpečnostní pojistka:</strong> potvrdit lze jen jedinou čekající bankovní platbu se současně shodným variabilním symbolem, částkou a měnou. Při potvrzení se kontrola zopakuje a Fio pohyb se k platbě jedinečně připoutá.</div>
<h2 class="h5 mt-4">Poslední importy</h2><div class="table-responsive"><table class="table table-sm table-striped bg-white"><thead><tr><th>ID</th><th>Období</th><th>Stav</th><th>Načteno</th><th>Nové</th><th>Duplicity</th><th>Návrhy</th><th>Kontrola</th><th>Chyba</th></tr></thead><tbody><?php foreach($runs as$run):?><tr><td><?=(int)$run['id']?></td><td><?=fioAdminH($run['period_from'])?> – <?=fioAdminH($run['period_to'])?></td><td><?=fioAdminH($run['status'])?></td><td><?=(int)$run['fetched_count']?></td><td><?=(int)$run['inserted_count']?></td><td><?=(int)$run['duplicate_count']?></td><td><?=(int)$run['proposed_count']?></td><td><?=(int)$run['review_count']?></td><td><code><?=fioAdminH($run['error_code'])?></code></td></tr><?php endforeach;?><?php if($runs===[]):?><tr><td colspan="9" class="text-muted">Import ještě neběžel.</td></tr><?php endif;?></tbody></table></div>
<h2 class="h5 mt-4">Importované pohyby</h2><div class="table-responsive"><table class="table table-sm table-hover align-middle bg-white"><thead><tr><th>Datum</th><th>ID Fio</th><th>Částka</th><th>VS</th><th>Výsledek</th><th>Cíl platby</th><th>Vysvětlení / potvrzení</th></tr></thead><tbody><?php foreach($movements as$movement):$label=$labels[$movement['match_status']]??[$movement['match_status'],'secondary'];$isCharge=($movement['payable_type']??'')==='member_charge';?><tr><td><?=fioAdminH($movement['booked_on'])?></td><td><code><?=fioAdminH($movement['fio_movement_id'])?></code></td><td><?=fioAdminMoney((int)$movement['amount_minor'],(string)$movement['currency'])?></td><td><?=fioAdminH($movement['variable_symbol']?:'—')?></td><td><span class="badge text-bg-<?=fioAdminH($label[1])?>"><?=fioAdminH($label[0])?></span><?php if($movement['confirmed_at']??null):?><div class="small text-muted"><?=fioAdminH($movement['confirmed_at'])?></div><?php endif;?></td><td><?php if($movement['candidate_order_id']):?><a href="eshop_payments_admin.php?q=<?=rawurlencode((string)($movement['public_code']??''))?>"><?=fioAdminH($movement['public_code']?:'#'.$movement['candidate_order_id'])?></a><?php elseif($isCharge&&$movement['payable_id']):?><a href="member_charges_admin.php?q=<?=rawurlencode((string)($movement['member_charge_code']??''))?>"><?=fioAdminH(($movement['member_charge_code']??'')?:'#'.$movement['payable_id'])?></a><div class="small text-muted"><?=fioAdminH($movement['member_charge_title']??'Členský předpis')?></div><?php else:?>—<?php endif;?></td><td style="min-width:330px"><div class="small mb-2"><?=fioAdminH($movement['match_reason'])?></div><?php if($movement['match_status']==='proposed_exact'):?><form method="post" class="row g-1"><?=csrf_field()?><input type="hidden" name="action" value="confirm_exact"><input type="hidden" name="movement_id" value="<?=(int)$movement['id']?>"><div class="col-12"><input class="form-control form-control-sm" name="reason" minlength="5" maxlength="1000" required value="Kontrola přesné shody s bankovním výpisem."></div><div class="col-8 form-check ms-2"><input class="form-check-input" type="checkbox" name="confirmed" value="1" id="fio-confirm-<?=(int)$movement['id']?>" required><label class="form-check-label small" for="fio-confirm-<?=(int)$movement['id']?>">Ověřil/a jsem VS, částku a měnu</label></div><div class="col-3 ms-auto d-grid"><button class="btn btn-sm btn-success">Potvrdit úhradu</button></div></form><?php elseif($movement['confirmation_note']??null):?><div class="small text-muted">Poznámka: <?=fioAdminH($movement['confirmation_note'])?></div><?php endif;?></td></tr><?php endforeach;?><?php if($movements===[]):?><tr><td colspan="7" class="text-muted">Žádné pohyby.</td></tr><?php endif;?></tbody></table></div></main></body></html>
