<?php
declare(strict_types=1);

require_once __DIR__ . '/includes/init.php';
require_once __DIR__ . '/csrf_helper.php';
require_once __DIR__ . '/includes/club_event.php';
if (!isset($_SESSION['trener_id']) || !roleAtLeast('admin')) { header('Location: login.php'); exit; }
function eventAdminH(mixed $value): string { return htmlspecialchars((string)$value,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8'); }
$errors=[];
if ($_SERVER['REQUEST_METHOD']==='POST') {
    if (!csrf_verify((string)($_POST['csrf_token']??''))) $errors[]='Formulář vypršel. Obnovte stránku.';
    else {
        try {
            $action=(string)($_POST['action']??'');$eventId=(int)($_POST['event_id']??0);$actor=(int)$_SESSION['trener_id'];
            if ($action==='create') {
                $result=clubEventCreateDraft($pdo,$actor,$_POST);$eventId=$result['id'];$_SESSION['flash_event_success']='Pracovní klubová akce byla založena.';
            } elseif ($action==='add_session') {
                clubEventAddSession($pdo,$eventId,$actor,(string)($_POST['starts_at']??''),(string)($_POST['ends_at']??''),(string)($_POST['location']??''),($_POST['capacity_override']??'')===''?null:(int)$_POST['capacity_override']);$_SESSION['flash_event_success']='Termín byl přidán.';
            } elseif ($action==='link_product') {
                $result=clubEventLinkProduct($pdo,$eventId,(int)($_POST['product_id']??0),$actor,(string)($_POST['note']??''));$_SESSION['flash_event_success']=$result['created']?'Produkt byl propojen s akcí.':'Produkt už byl s akcí propojen.';
            } elseif ($action==='unlink_product') {
                clubEventUnlinkProduct($pdo,$eventId,(int)($_POST['link_id']??0),$actor,(string)($_POST['note']??''));$_SESSION['flash_event_success']='Produkt byl od akce odpojen.';
            } else throw new InvalidArgumentException('Neplatná akce.');
            header('Location: eshop_events_admin.php?event_id='.$eventId,true,303);exit;
        } catch (PDOException $exception) { error_log('eshop_events_admin.php: '.$exception->getMessage());$errors[]='Databázová operace selhala bez částečného zápisu.'; }
        catch (InvalidArgumentException|ClubEventException $exception) { $errors[]=$exception->getMessage(); }
    }
}
$success=(string)($_SESSION['flash_event_success']??'');unset($_SESSION['flash_event_success']);
$events=clubEventList($pdo);$eventId=max(0,(int)($_GET['event_id']??0));if ($eventId===0&&$events!==[])$eventId=(int)$events[0]['id'];$detail=$eventId?clubEventDetail($pdo,$eventId):null;
$products=$pdo->query("SELECT p.id,p.name,p.offer_type,p.catalog_status FROM shop_products p WHERE p.offer_type IN ('club_event','camp') AND NOT EXISTS (SELECT 1 FROM shop_product_event_links l WHERE l.product_id=p.id) ORDER BY p.name,p.id")->fetchAll(PDO::FETCH_ASSOC);
?>
<!doctype html><html lang="cs"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Klubové akce K3</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" rel="stylesheet"></head><body class="bg-light">
<?php include __DIR__.'/hlavicka.php'; ?><main class="container-fluid py-4" style="max-width:1450px"><div class="d-flex justify-content-between align-items-center mb-3"><div><h1 class="h4 mb-0"><i class="bi bi-calendar-event me-2 text-primary"></i>Klubové akce K3</h1><div class="small text-muted">Pracovní model akcí, termínů, kapacit a vazeb na katalog.</div></div><a href="eshop_admin.php" class="btn btn-outline-secondary btn-sm">Administrace e-shopu</a></div>
<div class="alert alert-warning"><strong>Všechny akce zůstávají ve stavu draft.</strong> Tento krok nevytváří přihlášku, platbu, soupisku ani zápis do KIS.</div><?php foreach($errors as $error):?><div class="alert alert-danger"><?=eventAdminH($error)?></div><?php endforeach;?><?php if($success!==''):?><div class="alert alert-success"><?=eventAdminH($success)?></div><?php endif;?>
<div class="card border-0 shadow-sm mb-3"><div class="card-header bg-white fw-semibold">Založit pracovní akci</div><div class="card-body"><form method="post" class="row g-2"><?=csrf_field()?><input type="hidden" name="action" value="create"><div class="col-md-2"><label class="form-label">Kód</label><input class="form-control" name="code" maxlength="64" required placeholder="KROUZEK-2026"></div><div class="col-md-2"><label class="form-label">Typ</label><select class="form-select" name="event_type"><option value="club_event">Kroužek</option><option value="camp">Tábor</option></select></div><div class="col-md-4"><label class="form-label">Název</label><input class="form-control" name="name" maxlength="255" required></div><div class="col-md-4"><label class="form-label">Cílová skupina</label><input class="form-control" name="audience_label" maxlength="255" required placeholder="Děti 6–9 let, začátečníci"></div><div class="col-md-5"><label class="form-label">Popis jako prostý text</label><input class="form-control" name="description_plain" maxlength="2000"></div><div class="col-md-1"><label class="form-label">Věk od</label><input class="form-control" type="number" name="min_age" min="0" max="120"></div><div class="col-md-1"><label class="form-label">Věk do</label><input class="form-control" type="number" name="max_age" min="0" max="120"></div><div class="col-md-1"><label class="form-label">Kapacita</label><input class="form-control" type="number" name="capacity" min="1" max="10000" required></div><div class="col-md-2"><label class="form-label">Cena</label><select class="form-select" name="pricing_policy"><option value="free">Zdarma</option><option value="product_variants">Podle produktu</option></select></div><div class="col-md-1"><label class="form-label">Měna</label><input class="form-control" name="currency" value="CZK" maxlength="3" required></div><div class="col-md-3"><label class="form-label">Registrace od</label><input class="form-control" type="datetime-local" name="registration_starts_at"></div><div class="col-md-3"><label class="form-label">Registrace do</label><input class="form-control" type="datetime-local" name="registration_ends_at"></div><div class="col-md-3 d-grid align-self-end"><button class="btn btn-primary">Založit draft akce</button></div></form></div></div>
<div class="row g-3 mb-3"><?php foreach($events as $event):?><div class="col-md-4 col-xl-3"><a class="text-decoration-none text-reset" href="eshop_events_admin.php?event_id=<?=(int)$event['id']?>"><div class="card h-100 shadow-sm <?=$eventId===(int)$event['id']?'border-primary':'border-0'?>"><div class="card-body"><div class="d-flex justify-content-between"><strong><?=eventAdminH($event['name'])?></strong><span class="badge bg-warning text-dark">draft</span></div><code><?=eventAdminH($event['code'])?></code><div class="small text-muted mt-2"><?=(int)$event['session_count']?> termínů · <?=(int)$event['product_count']?> produktů · kapacita <?=(int)$event['capacity']?></div></div></div></a></div><?php endforeach;?></div>
<?php if($detail):$event=$detail['event'];?><div class="card border-0 shadow-sm mb-3"><div class="card-header bg-white"><strong><?=eventAdminH($event['name'])?></strong> <code><?=eventAdminH($event['event_type'])?></code></div><div class="card-body"><div class="row g-3"><div class="col-lg-6"><h2 class="h6">Přidat termín</h2><form method="post" class="row g-2"><?=csrf_field()?><input type="hidden" name="action" value="add_session"><input type="hidden" name="event_id" value="<?=$eventId?>"><div class="col-6"><input class="form-control" type="datetime-local" name="starts_at" required></div><div class="col-6"><input class="form-control" type="datetime-local" name="ends_at" required></div><div class="col-7"><input class="form-control" name="location" maxlength="255" required placeholder="Místo"></div><div class="col-3"><input class="form-control" type="number" name="capacity_override" min="1" max="10000" placeholder="Kapacita"></div><div class="col-2 d-grid"><button class="btn btn-outline-primary">Přidat</button></div></form><div class="mt-2"><?php foreach($detail['sessions'] as $session):?><div class="border-bottom py-2"><strong><?=eventAdminH($session['starts_at'])?> – <?=eventAdminH($session['ends_at'])?></strong><div class="small text-muted"><?=eventAdminH($session['location'])?><?=$session['capacity_override']?' · kapacita '.(int)$session['capacity_override']:''?></div></div><?php endforeach;?></div></div>
<div class="col-lg-6"><h2 class="h6">Propojit produkt stejného typu</h2><form method="post" class="row g-2"><?=csrf_field()?><input type="hidden" name="action" value="link_product"><input type="hidden" name="event_id" value="<?=$eventId?>"><div class="col-6"><select class="form-select" name="product_id" required><option value="">Vyberte produkt</option><?php foreach($products as $product):if($product['offer_type']!==$event['event_type'])continue;?><option value="<?=(int)$product['id']?>"><?=eventAdminH($product['name'])?> (<?=eventAdminH($product['catalog_status'])?>)</option><?php endforeach;?></select></div><div class="col-4"><input class="form-control" name="note" maxlength="1000" required placeholder="Důvod propojení"></div><div class="col-2 d-grid"><button class="btn btn-outline-success">Propojit</button></div></form><?php foreach($detail['products'] as $product):?><form method="post" class="d-flex gap-2 border-bottom py-2 align-items-center"><?=csrf_field()?><input type="hidden" name="action" value="unlink_product"><input type="hidden" name="event_id" value="<?=$eventId?>"><input type="hidden" name="link_id" value="<?=(int)$product['id']?>"><span class="flex-grow-1"><strong><?=eventAdminH($product['product_name'])?></strong> <code><?=eventAdminH($product['offer_type'])?></code></span><input class="form-control form-control-sm" style="max-width:220px" name="note" maxlength="1000" required placeholder="Důvod odpojení"><button class="btn btn-sm btn-outline-danger">Odpojit</button></form><?php endforeach;?></div></div></div></div>
<?php if($detail['events']!==[]):?><div class="card border-0 shadow-sm"><div class="card-header bg-white fw-semibold">Audit K3</div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Čas</th><th>Akce</th><th>Předmět</th><th>Kdo</th><th>Poznámka</th></tr></thead><tbody><?php foreach($detail['events'] as $audit):?><tr><td><?=eventAdminH($audit['created_at'])?></td><td><?=eventAdminH($audit['action'])?></td><td><?=eventAdminH($audit['subject_type'].' #'.$audit['subject_id'])?></td><td><?=eventAdminH($audit['actor_name']?:'#'.$audit['actor_trainer_id'])?></td><td><?=eventAdminH($audit['note'])?></td></tr><?php endforeach;?></tbody></table></div></div><?php endif;?><?php endif;?></main><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script></body></html>
