<?php
declare(strict_types=1);
require_once __DIR__.'/includes/init.php';require_once __DIR__.'/csrf_helper.php';require_once __DIR__.'/includes/kis_roster.php';
if(!isset($_SESSION['trener_id'])){header('Location: login.php');exit;}staffRequireActivePosition('registrar');
function rosterSettingsH(mixed$value):string{return htmlspecialchars((string)$value,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
$errors=[];$actorId=(int)$_SESSION['trener_id'];
if($_SERVER['REQUEST_METHOD']==='POST'){if(!csrf_verify((string)($_POST['csrf_token']??'')))$errors[]='Formulář vypršel. Obnovte stránku.';else try{$action=(string)($_POST['action']??'');$reason=(string)($_POST['reason']??'');$confirmed=isset($_POST['confirmed']);
    if($action==='rename_series')$result=kisRosterRenameSeries($pdo,(int)$_POST['series_id'],$actorId,(string)$_POST['name'],$reason,$confirmed);
    elseif($action==='archive_series')$result=kisRosterArchiveSeries($pdo,(int)$_POST['series_id'],$actorId,$reason,$confirmed);
    elseif($action==='rename_season')$result=kisRosterRenameSeason($pdo,(int)$_POST['season_id'],$actorId,(string)$_POST['name'],$reason,$confirmed);
    elseif($action==='close_season')$result=kisRosterCloseSeason($pdo,(int)$_POST['season_id'],$actorId,$reason,$confirmed);
    elseif($action==='update_team')$result=kisRosterUpdateTeam($pdo,(int)$_POST['team_id'],$actorId,(string)$_POST['name'],(string)$_POST['discipline'],(string)$_POST['age_label'],trim((string)($_POST['series_id']??''))===''?null:(int)$_POST['series_id'],$reason,$confirmed);
    elseif($action==='close_team')$result=kisRosterCloseTeam($pdo,(int)$_POST['team_id'],$actorId,$reason,$confirmed);else throw new InvalidArgumentException('Neznámá akce.');$_SESSION['roster_settings_flash']=$result['changed']?'Změna byla auditovaně uložena.':'Záznam se nezměnil.';header('Location: kis_roster_settings_admin.php',true,303);exit;
}catch(InvalidArgumentException|KisRosterException$exception){$errors[]=$exception->getMessage();}catch(Throwable$exception){error_log('kis_roster_settings_admin.php: '.$exception->getMessage());$errors[]='Operace selhala bez částečného zápisu.';}}
$success=(string)($_SESSION['roster_settings_flash']??'');unset($_SESSION['roster_settings_flash']);$series=kisRosterSeries($pdo);$seasons=kisRosterSeasons($pdo);$teams=kisRosterTeams($pdo);
?>
<!doctype html><html lang="cs"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Správa struktur soupisek</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"></head><body class="bg-light"><?php include __DIR__.'/hlavicka.php';?><main class="container-fluid py-4" style="max-width:1400px"><div class="d-flex justify-content-between mb-3"><div><h1 class="h4 mb-1">Správa sezon, sérií a soupisek</h1><p class="text-muted mb-0">Kódy, kalendáře a období jsou stabilní identita. Opravit lze názvy a údaje týmu; uzavření zachová historii.</p></div><a class="btn btn-outline-secondary btn-sm" href="kis_rosters_admin.php">Členové a roční obnova</a></div><?php foreach($errors as$error):?><div class="alert alert-danger"><?=rosterSettingsH($error)?></div><?php endforeach;?><?php if($success!==''):?><div class="alert alert-success"><?=rosterSettingsH($success)?></div><?php endif;?>
<div class="row g-3"><div class="col-xl-6"><div class="card border-0 shadow-sm mb-3"><div class="card-header bg-white fw-semibold">Stabilní série</div><div class="card-body"><?php foreach($series as$item):?><form method="post" class="row g-2 align-items-center border-bottom py-2"><?=csrf_field()?><input type="hidden" name="series_id" value="<?=(int)$item['id']?>"><div class="col-3"><code><?=rosterSettingsH($item['code'])?></code><div class="small text-muted"><?=rosterSettingsH($item['status'])?></div></div><div class="col-4"><input class="form-control form-control-sm" name="name" required value="<?=rosterSettingsH($item['name'])?>" <?=$item['status']!=='active'?'disabled':''?>></div><div class="col-3"><input class="form-control form-control-sm" name="reason" required placeholder="Důvod"></div><div class="col-2"><div class="form-check"><input class="form-check-input" type="checkbox" name="confirmed" value="1" required <?=$item['status']!=='active'?'disabled':''?>><label class="small">Potvrdit</label></div></div><?php if($item['status']==='active'):?><div class="col-6 d-grid"><button class="btn btn-sm btn-outline-primary" name="action" value="rename_series">Uložit název</button></div><div class="col-6 d-grid"><button class="btn btn-sm btn-outline-secondary" name="action" value="archive_series" <?=(int)$item['team_count']>0?'disabled':''?>>Archivovat (<?=(int)$item['team_count']?> týmů)</button></div><?php endif;?></form><?php endforeach;?></div></div>
<div class="card border-0 shadow-sm"><div class="card-header bg-white fw-semibold">Sezony</div><div class="card-body"><?php foreach($seasons as$item):?><form method="post" class="row g-2 align-items-center border-bottom py-2"><?=csrf_field()?><input type="hidden" name="season_id" value="<?=(int)$item['id']?>"><div class="col-3"><code><?=rosterSettingsH($item['code'])?></code><div class="small text-muted"><?=rosterSettingsH($item['starts_on'].' – '.$item['ends_on'].' / '.$item['status'])?></div></div><div class="col-4"><input class="form-control form-control-sm" name="name" required value="<?=rosterSettingsH($item['name'])?>" <?=$item['status']!=='active'?'disabled':''?>></div><div class="col-3"><input class="form-control form-control-sm" name="reason" required placeholder="Důvod"></div><div class="col-2 form-check"><input class="form-check-input" type="checkbox" name="confirmed" value="1" required <?=$item['status']!=='active'?'disabled':''?>><label class="small">Potvrdit</label></div><?php if($item['status']==='active'):?><div class="col-6 d-grid"><button class="btn btn-sm btn-outline-primary" name="action" value="rename_season">Uložit název</button></div><div class="col-6 d-grid"><button class="btn btn-sm btn-outline-secondary" name="action" value="close_season" <?=(int)$item['team_count']>0?'disabled':''?>>Uzavřít (<?=(int)$item['team_count']?> týmů)</button></div><?php endif;?></form><?php endforeach;?></div></div></div>
<div class="col-xl-6"><div class="card border-0 shadow-sm"><div class="card-header bg-white fw-semibold">Roční týmové soupisky</div><div class="card-body"><?php foreach($teams as$item):?><form method="post" class="row g-2 align-items-end border-bottom py-3"><?=csrf_field()?><input type="hidden" name="team_id" value="<?=(int)$item['id']?>"><div class="col-4"><label class="form-label small"><?=rosterSettingsH($item['season_name'])?> · <?=rosterSettingsH($item['code'])?></label><input class="form-control form-control-sm" name="name" required value="<?=rosterSettingsH($item['name'])?>" <?=$item['status']!=='active'?'disabled':''?>></div><div class="col-3"><label class="form-label small">Disciplína</label><input class="form-control form-control-sm" name="discipline" required value="<?=rosterSettingsH($item['discipline'])?>" <?=$item['status']!=='active'?'disabled':''?>></div><div class="col-2"><label class="form-label small">Kategorie</label><input class="form-control form-control-sm" name="age_label" required value="<?=rosterSettingsH($item['age_label'])?>" <?=$item['status']!=='active'?'disabled':''?>></div><div class="col-3"><label class="form-label small">Série</label><select class="form-select form-select-sm" name="series_id" <?=$item['status']!=='active'?'disabled':''?>><option value="">Bez série</option><?php foreach($series as$s):if($s['status']!=='active')continue;?><option value="<?=(int)$s['id']?>" <?=($item['series_id']!==null&&(int)$item['series_id']===(int)$s['id'])?'selected':''?>><?=rosterSettingsH($s['name'])?></option><?php endforeach;?></select></div><div class="col-7"><input class="form-control form-control-sm" name="reason" required placeholder="Auditovaný důvod"></div><div class="col-2 form-check"><input class="form-check-input" type="checkbox" name="confirmed" value="1" required <?=$item['status']!=='active'?'disabled':''?>><label class="small">Potvrdit</label></div><?php if($item['status']==='active'):?><div class="col-3 d-flex gap-1"><button class="btn btn-sm btn-outline-primary" name="action" value="update_team">Uložit</button><button class="btn btn-sm btn-outline-secondary" name="action" value="close_team" <?=(int)$item['member_count']>0?'disabled':''?>>Uzavřít</button></div><?php endif;?></form><?php endforeach;?></div></div></div></div></main></body></html>
