<?php
declare(strict_types=1);
require_once __DIR__.'/includes/init.php';require_once __DIR__.'/csrf_helper.php';require_once __DIR__.'/includes/kis_roster.php';
if(!isset($_SESSION['trener_id'])||!canAccess('sync_evidence')){header('Location: login.php');exit;}
function krh(mixed$value):string{return htmlspecialchars((string)$value,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
function krNullableInt(mixed$value):?int{$text=trim((string)$value);return$text===''?null:(int)$text;}
$errors=[];$actorId=(int)$_SESSION['trener_id'];
if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!csrf_verify((string)($_POST['csrf_token']??'')))$errors[]='Formular vyprsel. Obnovte stranku.';
    else try{
        $action=(string)($_POST['action']??'');
        if($action==='create_series'){$result=kisRosterCreateSeries($pdo,$actorId,(string)$_POST['code'],(string)$_POST['name'],(string)$_POST['series_type'],(string)$_POST['season_type'],(string)$_POST['rollover_policy'],krNullableInt($_POST['next_series_id']??null),krNullableInt($_POST['age_from']??null),krNullableInt($_POST['age_to']??null),krNullableInt($_POST['birth_year_from']??null),krNullableInt($_POST['birth_year_to']??null));$_SESSION['flash_success']='Serie '.$result['name'].' je pripravena.';}
        elseif($action==='create_season'){$result=kisRosterCreateSeason($pdo,$actorId,(string)$_POST['code'],(string)$_POST['name'],(string)$_POST['starts_on'],(string)$_POST['ends_on'],(string)$_POST['season_type']);$_SESSION['flash_success']='Sezona '.$result['name'].' je pripravena.';}
        elseif($action==='create_team'){$result=kisRosterCreateTeam($pdo,(int)$_POST['season_id'],$actorId,(string)$_POST['code'],(string)$_POST['name'],(string)$_POST['discipline'],(string)$_POST['age_label'],(string)$_POST['note'],krNullableInt($_POST['series_id']??null));$_SESSION['flash_success']='Tym '.$result['name'].' byl vytvoren.';}
        elseif($action==='add_member'){$result=kisRosterAddMember($pdo,(int)$_POST['team_id'],(int)$_POST['sportovec_id'],$actorId,'manual',(string)$_POST['valid_from'],(string)$_POST['note']);$_SESSION['flash_success']=$result['created']?'Sportovec byl pridan na soupisku.':'Sportovec uz je na aktivni soupisce.';}
        elseif($action==='remove_member'){$result=kisRosterRemoveMember($pdo,(int)$_POST['member_id'],$actorId,(string)$_POST['valid_to'],(string)$_POST['note']);$_SESSION['flash_success']=$result['changed']?'Sportovec byl ze soupisky odebran.':'Sportovec uz byl odebran.';}
        elseif($action==='set_rollover_exception'){if(!roleAtLeast('admin'))throw new KisRosterException('Pro vyjimku je nutna role admin.');$result=kisRosterSetRolloverException($pdo,(int)$_POST['team_id'],(int)$_POST['target_season_id'],(int)$_POST['sportovec_id'],(string)$_POST['exception_action'],krNullableInt($_POST['target_team_id']??null),$actorId,(string)$_POST['reason'],($_POST['confirm_exception']??'')==='1');$_SESSION['flash_success']=$result['created']?'Vyjimka byla auditovane ulozena.':'Vyjimka byla auditovane aktualizovana.';}
        elseif($action==='execute_rollover'){if(!roleAtLeast('admin'))throw new KisRosterException('Pro provedeni obnovy je nutna role admin.');$result=kisRosterExecuteRollover($pdo,(int)$_POST['team_id'],(int)$_POST['target_season_id'],$actorId,(string)$_POST['reason'],($_POST['confirm_rollover']??'')==='1',(string)$_POST['preview_fingerprint']);$_SESSION['flash_success']=$result['idempotent']?'Tento nahled uz byl drive proveden; zadny dalsi zapis nevznikl.':'Obnova dokoncena: '.$result['moved_count'].' presunuto, '.$result['skipped_count'].' beze zmeny.';}
        else throw new InvalidArgumentException('Neznama akce soupisky.');
        $target=(int)($_POST['team_id']??0);$targetSeason=(int)($_POST['target_season_id']??0);$query=$target>0?'?team_id='.$target.($targetSeason>0?'&preview_season_id='.$targetSeason:''):'';header('Location: kis_rosters_admin.php'.$query);exit;
    }catch(InvalidArgumentException|KisRosterException$exception){$errors[]=$exception->getMessage();}catch(Throwable$exception){error_log('kis_rosters_admin.php: '.$exception->getMessage());$errors[]='Operace selhala bez castecneho zapisu.';}
}
$success=(string)($_SESSION['flash_success']??'');unset($_SESSION['flash_success']);$series=kisRosterSeries($pdo);$seasons=kisRosterSeasons($pdo);$teams=kisRosterTeams($pdo);$teamId=max(0,(int)($_GET['team_id']??0));$detail=$teamId>0?kisRosterTeamDetail($pdo,$teamId):['team'=>null,'members'=>[],'events'=>[]];$preview=null;$previewSeasonId=max(0,(int)($_GET['preview_season_id']??0));if($teamId>0&&$previewSeasonId>0)try{$preview=kisRosterPreviewRollover($pdo,$teamId,$previewSeasonId);}catch(Throwable$e){$errors[]=$e->getMessage();}$people=$pdo->query("SELECT id,jmeno,prijmeni,narozeni,uciid,stav_clenstvi FROM sportovci WHERE stav_clenstvi<>'archiv' ORDER BY prijmeni,jmeno,id")->fetchAll(PDO::FETCH_ASSOC);$today=(new DateTimeImmutable('today'))->format('Y-m-d');
?>
<!doctype html><html lang="cs"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>KIS soupisky</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"></head><body class="bg-light"><?php include __DIR__.'/hlavicka.php';?><main class="container-fluid py-4" style="max-width:1500px"><div class="d-flex justify-content-between mb-3"><div><h1 class="h4 mb-0">KIS - serie, sezony a soupisky</h1><div class="small text-muted">Nahled nic nemeni. Skutecna obnova vyzaduje admina, duvod a explicitni potvrzeni.</div></div><a href="kis_sync_center.php" class="btn btn-outline-secondary btn-sm">Synchronizacni centrum</a></div>
<?php foreach($errors as$error):?><div class="alert alert-danger"><?=krh($error)?></div><?php endforeach;?><?php if($success!==''):?><div class="alert alert-success"><?=krh($success)?></div><?php endif;?>
<div class="row g-3"><div class="col-xl-4">
<div class="card mb-3"><div class="card-header fw-semibold">Nova stabilni serie</div><div class="card-body"><form method="post" class="row g-2"><input type="hidden" name="csrf_token" value="<?=krh(csrf_token())?>"><input type="hidden" name="action" value="create_series"><div class="col-4"><label class="form-label">Kod</label><input class="form-control" name="code" placeholder="U15" required></div><div class="col-8"><label class="form-label">Nazev</label><input class="form-control" name="name" required></div><div class="col-6"><label class="form-label">Typ</label><select class="form-select" name="series_type"><option value="hobby">Krouzek</option><option value="age">Vekova</option><option value="discipline">Disciplina</option><option value="special">Specialni</option></select></div><div class="col-6"><label class="form-label">Kalendar</label><select class="form-select" name="season_type"><option value="school_year">Skolni rok</option><option value="calendar_year">Kalendarni rok</option></select></div><div class="col-12"><label class="form-label">Obnova</label><select class="form-select" name="rollover_policy"><option value="renewal_required">Vyžaduje prodlouzeni</option><option value="age_progression">Vekovy postup</option><option value="carry_forward">Prenest</option><option value="manual">Rucne</option></select></div><div class="col-12"><label class="form-label">Nasledna vekova serie (volitelne)</label><select class="form-select" name="next_series_id"><option value="">Bez naslednika</option><?php foreach($series as$s):if($s['series_type']!=='age')continue;?><option value="<?=(int)$s['id']?>"><?=krh($s['name'])?></option><?php endforeach;?></select></div><div class="col-6"><label class="form-label">Vek od/do</label><div class="input-group"><input type="number" min="0" max="120" class="form-control" name="age_from"><input type="number" min="0" max="120" class="form-control" name="age_to"></div></div><div class="col-6"><label class="form-label">Rocnik od/do</label><div class="input-group"><input type="number" min="1900" max="2200" class="form-control" name="birth_year_from"><input type="number" min="1900" max="2200" class="form-control" name="birth_year_to"></div></div><div><button class="btn btn-primary btn-sm">Vytvorit serii</button></div></form></div></div>
<div class="card mb-3"><div class="card-header fw-semibold">Nova sezona</div><div class="card-body"><form method="post" class="row g-2"><input type="hidden" name="csrf_token" value="<?=krh(csrf_token())?>"><input type="hidden" name="action" value="create_season"><div class="col-4"><label class="form-label">Kod</label><input class="form-control" name="code" required></div><div class="col-8"><label class="form-label">Nazev</label><input class="form-control" name="name" required></div><div class="col-12"><label class="form-label">Typ</label><select class="form-select" name="season_type"><option value="school_year">Skolni rok</option><option value="calendar_year">Kalendarni rok</option></select></div><div class="col-6"><label class="form-label">Od</label><input type="date" class="form-control" name="starts_on" required></div><div class="col-6"><label class="form-label">Do</label><input type="date" class="form-control" name="ends_on" required></div><div><button class="btn btn-primary btn-sm">Vytvorit sezonu</button></div></form></div></div>
<div class="card"><div class="card-header fw-semibold">Nova rocni soupiska</div><div class="card-body"><form method="post" class="row g-2"><input type="hidden" name="csrf_token" value="<?=krh(csrf_token())?>"><input type="hidden" name="action" value="create_team"><div class="col-12"><label class="form-label">Serie</label><select class="form-select" name="series_id"><option value="">Legacy tym bez serie</option><?php foreach($series as$s):?><option value="<?=(int)$s['id']?>"><?=krh($s['name'].' / '.$s['season_type'].' / '.$s['rollover_policy'])?></option><?php endforeach;?></select></div><div class="col-12"><label class="form-label">Sezona</label><select class="form-select" name="season_id" required><option value="">Vyberte</option><?php foreach($seasons as$s):?><option value="<?=(int)$s['id']?>"><?=krh($s['name'].' / '.$s['season_type'])?></option><?php endforeach;?></select></div><div class="col-4"><label class="form-label">Kod</label><input class="form-control" name="code" required></div><div class="col-8"><label class="form-label">Nazev</label><input class="form-control" name="name" required></div><div class="col-6"><label class="form-label">Disciplina</label><input class="form-control" name="discipline" required></div><div class="col-6"><label class="form-label">Kategorie</label><input class="form-control" name="age_label" required></div><div class="col-12"><label class="form-label">Duvod</label><input class="form-control" name="note" value="Zalozeni rocni soupisky." required></div><div><button class="btn btn-primary btn-sm">Vytvorit soupisku</button></div></form></div></div></div>
<div class="col-xl-8"><div class="card mb-3"><div class="card-header fw-semibold">Stabilni serie</div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Serie</th><th>Typ</th><th>Kalendar</th><th>Obnova</th><th>Nasleduje</th></tr></thead><tbody><?php foreach($series as$s):?><tr><td><?=krh($s['name'])?> <code><?=krh($s['code'])?></code></td><td><?=krh($s['series_type'])?></td><td><?=krh($s['season_type'])?></td><td><?=krh($s['rollover_policy'])?></td><td><?=krh($s['next_series_name']??'-')?></td></tr><?php endforeach;?></tbody></table></div></div>
<div class="card mb-3"><div class="card-header fw-semibold">Rocni soupisky</div><div class="table-responsive"><table class="table table-sm table-hover mb-0"><thead><tr><th>Sezona</th><th>Serie</th><th>Tym</th><th>Politika</th><th>Clenu</th><th></th></tr></thead><tbody><?php foreach($teams as$t):?><tr><td><?=krh($t['season_name'].' / '.$t['season_type'])?></td><td><?=krh($t['series_name']??'legacy')?></td><td><?=krh($t['name'])?> <code><?=krh($t['code'])?></code></td><td><?=krh($t['rollover_policy']??'manual')?></td><td><?=(int)$t['member_count']?></td><td><a class="btn btn-outline-primary btn-sm" href="?team_id=<?=(int)$t['id']?>">Soupiska</a></td></tr><?php endforeach;?></tbody></table></div></div>
<?php if($detail['team']):$team=$detail['team'];?><div class="card mb-3"><div class="card-header"><strong><?=krh($team['name'])?></strong> / <?=krh($team['season_name'])?> / <?=krh($team['series_name']??'legacy')?></div><div class="card-body border-bottom"><form method="post" class="row g-2 align-items-end"><input type="hidden" name="csrf_token" value="<?=krh(csrf_token())?>"><input type="hidden" name="action" value="add_member"><input type="hidden" name="team_id" value="<?=(int)$team['id']?>"><div class="col-lg-5"><label class="form-label">Sportovec</label><select class="form-select" name="sportovec_id" required><?php foreach($people as$p):?><option value="<?=(int)$p['id']?>"><?=krh($p['prijmeni'].' '.$p['jmeno'])?></option><?php endforeach;?></select></div><div class="col-lg-2"><label class="form-label">Plati od</label><input type="date" class="form-control" name="valid_from" value="<?=krh($today)?>" required></div><div class="col-lg-4"><label class="form-label">Duvod</label><input class="form-control" name="note" value="Rucni zarazeni." required></div><div class="col-lg-1"><button class="btn btn-success btn-sm">Pridat</button></div></form></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Sportovec</th><th>Stav</th><th>Platnost</th><th></th></tr></thead><tbody><?php foreach($detail['members']as$m):?><tr><td><?=krh($m['prijmeni'].' '.$m['jmeno'])?></td><td><?=krh($m['status'].' / '.$m['source'])?></td><td><?=krh($m['valid_from'].' - '.($m['valid_to']?:'dosud'))?></td><td><?php if($m['status']==='active'):?><form method="post" class="d-flex gap-1"><input type="hidden" name="csrf_token" value="<?=krh(csrf_token())?>"><input type="hidden" name="action" value="remove_member"><input type="hidden" name="team_id" value="<?=(int)$team['id']?>"><input type="hidden" name="member_id" value="<?=(int)$m['id']?>"><input type="hidden" name="valid_to" value="<?=krh($today)?>"><input class="form-control form-control-sm" name="note" value="Rucni odebrani." required><button class="btn btn-outline-danger btn-sm">Odebrat</button></form><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></div>
<div class="card"><div class="card-header fw-semibold">Read-only nahled obnovy</div><div class="card-body">
<form method="get" class="row g-2"><input type="hidden" name="team_id" value="<?=(int)$team['id']?>"><div class="col-9"><select class="form-select" name="preview_season_id" required><option value="">Cilova sezona</option><?php foreach($seasons as$s):?><option value="<?=(int)$s['id']?>" <?=$previewSeasonId===(int)$s['id']?'selected':''?>><?=krh($s['name'].' / '.$s['season_type'])?></option><?php endforeach;?></select></div><div class="col-3"><button class="btn btn-outline-primary">Zobrazit nahled</button></div></form>
<?php if($preview):$targetTeams=array_values(array_filter($teams,static fn(array$t):bool=>(int)$t['season_id']===$previewSeasonId&&$t['status']==='active'));?>
<p class="mt-3 mb-1">Politika: <code><?=krh($preview['policy'])?></code>; fingerprint: <code><?=krh(substr($preview['fingerprint'],0,12))?>…</code>; provedeni: <strong><?=(int)$preview['executable_count']?></strong></p>
<div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>Sportovec</th><th>Navrh</th><th>Cilova soupiska</th><th>Individualni vyjimka</th></tr></thead><tbody><?php foreach($preview['proposals']as$p):?><tr><td><?=krh($p['name'])?></td><td><?=krh($p['action'])?></td><td><?=krh($p['target_team_id']??'-')?></td><td><?php if(roleAtLeast('admin')):?><form method="post" class="row g-1"><input type="hidden" name="csrf_token" value="<?=krh(csrf_token())?>"><input type="hidden" name="action" value="set_rollover_exception"><input type="hidden" name="team_id" value="<?=(int)$team['id']?>"><input type="hidden" name="target_season_id" value="<?=$previewSeasonId?>"><input type="hidden" name="sportovec_id" value="<?=(int)$p['sportovec_id']?>"><div class="col-4"><select class="form-select form-select-sm" name="exception_action"><option value="skip">Preskocit</option><option value="target_override">Jiny cil</option></select></div><div class="col-4"><select class="form-select form-select-sm" name="target_team_id"><option value="">Bez cile</option><?php foreach($targetTeams as$tt):?><option value="<?=(int)$tt['id']?>"><?=krh($tt['name'])?></option><?php endforeach;?></select></div><div class="col-4"><input class="form-control form-control-sm" name="reason" placeholder="Duvod" required></div><div class="col-12 form-check ms-1"><input class="form-check-input" type="checkbox" name="confirm_exception" value="1" required><label class="form-check-label small">Potvrzuji vyjimku</label><button class="btn btn-outline-secondary btn-sm ms-2">Ulozit</button></div></form><?php endif;?></td></tr><?php endforeach;?></tbody></table></div>
<?php if(roleAtLeast('admin')):?><form method="post" class="border rounded p-3 bg-white"><input type="hidden" name="csrf_token" value="<?=krh(csrf_token())?>"><input type="hidden" name="action" value="execute_rollover"><input type="hidden" name="team_id" value="<?=(int)$team['id']?>"><input type="hidden" name="target_season_id" value="<?=$previewSeasonId?>"><input type="hidden" name="preview_fingerprint" value="<?=krh($preview['fingerprint'])?>"><label class="form-label">Duvod provedeni</label><input class="form-control mb-2" name="reason" required><div class="form-check mb-2"><input class="form-check-input" type="checkbox" name="confirm_rollover" value="1" required><label class="form-check-label">Potvrzuji skutecne ukonceni zdrojovych a otevreni cilovych clenstvi.</label></div><button class="btn btn-danger">Provest tento nahled</button></form><?php endif;?>
<?php endif;?></div></div><?php endif;?></div></div></main></body></html>
