<?php
declare(strict_types=1);
require_once __DIR__.'/includes/init.php';require_once __DIR__.'/csrf_helper.php';require_once __DIR__.'/includes/kis_roster.php';
if(!isset($_SESSION['trener_id'])||!canAccess('sync_evidence')){header('Location: login.php');exit;}
function krh(mixed$value):string{return htmlspecialchars((string)$value,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
$errors=[];$actorId=(int)$_SESSION['trener_id'];
if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!csrf_verify((string)($_POST['csrf_token']??'')))$errors[]='Formulář vypršel. Obnovte stránku.';
    else try{$action=(string)($_POST['action']??'');
        if($action==='create_season'){$result=kisRosterCreateSeason($pdo,$actorId,(string)$_POST['code'],(string)$_POST['name'],(string)$_POST['starts_on'],(string)$_POST['ends_on']);$_SESSION['flash_success']='Sezóna '.(string)$result['name'].' je připravena.';}
        elseif($action==='create_team'){$result=kisRosterCreateTeam($pdo,(int)$_POST['season_id'],$actorId,(string)$_POST['code'],(string)$_POST['name'],(string)$_POST['discipline'],(string)$_POST['age_label'],(string)$_POST['note']);$_SESSION['flash_success']='Tým '.(string)$result['name'].' byl vytvořen.';}
        elseif($action==='add_member'){$result=kisRosterAddMember($pdo,(int)$_POST['team_id'],(int)$_POST['sportovec_id'],$actorId,'manual',(string)$_POST['valid_from'],(string)$_POST['note']);$_SESSION['flash_success']=$result['created']?'Sportovec byl přidán na soupisku.':'Sportovec už je na aktivní soupisce.';}
        elseif($action==='remove_member'){$result=kisRosterRemoveMember($pdo,(int)$_POST['member_id'],$actorId,(string)$_POST['valid_to'],(string)$_POST['note']);$_SESSION['flash_success']=$result['changed']?'Sportovec byl ze soupisky odebrán.':'Sportovec už byl odebrán.';}
        else throw new InvalidArgumentException('Neznámá akce soupisky.');
        $target=(int)($_POST['team_id']??0);header('Location: kis_rosters_admin.php'.($target>0?'?team_id='.$target:''));exit;
    }catch(InvalidArgumentException|KisRosterException$exception){$errors[]=$exception->getMessage();}catch(Throwable$exception){error_log('kis_rosters_admin.php: '.$exception->getMessage());$errors[]='Operace selhala bez částečného zápisu.';}
}
$success=(string)($_SESSION['flash_success']??'');unset($_SESSION['flash_success']);$seasons=kisRosterSeasons($pdo);$teams=kisRosterTeams($pdo);$teamId=max(0,(int)($_GET['team_id']??0));$detail=$teamId>0?kisRosterTeamDetail($pdo,$teamId):['team'=>null,'members'=>[],'events'=>[]];$people=$pdo->query("SELECT id,jmeno,prijmeni,narozeni,uciid,stav_clenstvi FROM sportovci WHERE stav_clenstvi<>'archiv' ORDER BY prijmeni,jmeno,id")->fetchAll(PDO::FETCH_ASSOC);$today=(new DateTimeImmutable('today'))->format('Y-m-d');
?>
<!doctype html><html lang="cs"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>KIS týmy a soupisky</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"></head><body class="bg-light"><?php include __DIR__.'/hlavicka.php';?><main class="container-fluid py-4" style="max-width:1450px"><div class="d-flex justify-content-between align-items-center mb-3"><div><h1 class="h4 mb-0">KIS – sezóny, týmy a soupisky</h1><div class="small text-muted">Interní evidence v shadow režimu. Do externího KIS se nic nezapisuje.</div></div><a href="kis_sync_center.php" class="btn btn-outline-secondary btn-sm">Synchronizační centrum</a></div>
<?php foreach($errors as$error):?><div class="alert alert-danger"><?=krh($error)?></div><?php endforeach;?><?php if($success!==''):?><div class="alert alert-success"><?=krh($success)?></div><?php endif;?>
<div class="row g-3"><div class="col-xl-4"><div class="card mb-3"><div class="card-header fw-semibold">Nová sezóna</div><div class="card-body"><form method="post" class="row g-2"><input type="hidden" name="csrf_token" value="<?=krh(csrf_token())?>"><input type="hidden" name="action" value="create_season"><div class="col-4"><label class="form-label">Kód</label><input class="form-control" name="code" placeholder="2026-27" required></div><div class="col-8"><label class="form-label">Název</label><input class="form-control" name="name" placeholder="Sezóna 2026/27" required></div><div class="col-6"><label class="form-label">Od</label><input type="date" class="form-control" name="starts_on" required></div><div class="col-6"><label class="form-label">Do</label><input type="date" class="form-control" name="ends_on" required></div><div><button class="btn btn-primary btn-sm">Vytvořit sezónu</button></div></form></div></div>
<div class="card"><div class="card-header fw-semibold">Nový tým</div><div class="card-body"><form method="post" class="row g-2"><input type="hidden" name="csrf_token" value="<?=krh(csrf_token())?>"><input type="hidden" name="action" value="create_team"><div class="col-12"><label class="form-label">Sezóna</label><select class="form-select" name="season_id" required><option value="">Vyberte</option><?php foreach($seasons as$s):?><option value="<?=(int)$s['id']?>"><?=krh($s['name'])?></option><?php endforeach;?></select></div><div class="col-4"><label class="form-label">Kód</label><input class="form-control" name="code" required></div><div class="col-8"><label class="form-label">Název</label><input class="form-control" name="name" required></div><div class="col-6"><label class="form-label">Disciplína</label><input class="form-control" name="discipline" value="Dráha" required></div><div class="col-6"><label class="form-label">Kategorie</label><input class="form-control" name="age_label" placeholder="U15" required></div><div class="col-12"><label class="form-label">Důvod</label><input class="form-control" name="note" value="Založení interního týmu." required></div><div><button class="btn btn-primary btn-sm">Vytvořit tým</button></div></form></div></div></div>
<div class="col-xl-8"><div class="card mb-3"><div class="card-header fw-semibold">Týmy</div><div class="table-responsive"><table class="table table-sm table-hover mb-0"><thead><tr><th>Sezóna</th><th>Tým</th><th>Disciplína</th><th>Kategorie</th><th>Aktivní</th><th></th></tr></thead><tbody><?php foreach($teams as$t):?><tr><td><?=krh($t['season_name'])?></td><td><?=krh($t['name'])?> <code><?=krh($t['code'])?></code></td><td><?=krh($t['discipline'])?></td><td><?=krh($t['age_label'])?></td><td><?=(int)$t['member_count']?></td><td><a class="btn btn-outline-primary btn-sm" href="?team_id=<?=(int)$t['id']?>">Soupiska</a></td></tr><?php endforeach;?><?php if($teams===[]):?><tr><td colspan="6" class="text-muted">Nejdříve založte sezónu a tým.</td></tr><?php endif;?></tbody></table></div></div>
<?php if($detail['team']):$team=$detail['team'];?><div class="card"><div class="card-header"><strong><?=krh($team['name'])?></strong> · <?=krh($team['season_name'])?> <span class="badge bg-secondary"><?=krh($team['discipline'])?> / <?=krh($team['age_label'])?></span></div><div class="card-body border-bottom"><form method="post" class="row g-2 align-items-end"><input type="hidden" name="csrf_token" value="<?=krh(csrf_token())?>"><input type="hidden" name="action" value="add_member"><input type="hidden" name="team_id" value="<?=(int)$team['id']?>"><div class="col-lg-6"><label class="form-label">Sportovec</label><select class="form-select" name="sportovec_id" required><option value="">Vyberte sportovce</option><?php foreach($people as$p):?><option value="<?=(int)$p['id']?>"><?=krh($p['prijmeni'].' '.$p['jmeno'].' · '.($p['uciid']?:'bez UCI').' · '.$p['stav_clenstvi'])?></option><?php endforeach;?></select></div><div class="col-lg-2"><label class="form-label">Platí od</label><input type="date" class="form-control" name="valid_from" value="<?=krh($today)?>" required></div><div class="col-lg-3"><label class="form-label">Důvod</label><input class="form-control" name="note" value="Ruční zařazení do interní soupisky." required></div><div class="col-lg-1"><button class="btn btn-success btn-sm">Přidat</button></div></form></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Sportovec</th><th>UCI snapshot</th><th>Stav</th><th>Platnost</th><th></th></tr></thead><tbody><?php foreach($detail['members']as$m):?><tr><td><?=krh($m['prijmeni'].' '.$m['jmeno'])?> <span class="small text-muted"><?=krh($m['stav_clenstvi'])?></span></td><td><code><?=krh($m['kis_external_id_snapshot']?:'—')?></code></td><td><?=krh($m['status'])?> / <?=krh($m['source'])?></td><td><?=krh($m['valid_from'])?> – <?=krh($m['valid_to']?:'dosud')?></td><td><?php if($m['status']==='active'):?><form method="post" class="d-flex gap-1"><input type="hidden" name="csrf_token" value="<?=krh(csrf_token())?>"><input type="hidden" name="action" value="remove_member"><input type="hidden" name="team_id" value="<?=(int)$team['id']?>"><input type="hidden" name="member_id" value="<?=(int)$m['id']?>"><input type="hidden" name="valid_to" value="<?=krh($today)?>"><input class="form-control form-control-sm" name="note" value="Odebrání z interní soupisky." required><button class="btn btn-outline-danger btn-sm">Odebrat</button></form><?php endif;?></td></tr><?php endforeach;?><?php if($detail['members']===[]):?><tr><td colspan="5" class="text-muted">Soupiska je prázdná.</td></tr><?php endif;?></tbody></table></div></div><?php endif;?></div></div></main></body></html>
