<?php
declare(strict_types=1);
require_once __DIR__ . '/includes/init.php';
require_once __DIR__ . '/csrf_helper.php';
require_once __DIR__ . '/includes/member_fee_plan.php';

if (!isset($_SESSION['trener_id'])) { header('Location: login.php'); exit; }
staffRequireActivePosition('finance_manager');

function mfph(mixed $value): string { return htmlspecialchars((string)$value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); }
function mfpAmount(string $value): int { $value=str_replace([' ', ','],['','.'],trim($value));if(preg_match('/^[0-9]+(?:\.[0-9]{1,2})?$/D',$value)!==1)throw new InvalidArgumentException('Částka musí být číslo s nejvýše dvěma desetinnými místy.');[$whole,$decimal]=array_pad(explode('.',$value,2),2,'');return(int)$whole*100+(int)str_pad($decimal,2,'0'); }

$actorId=(int)$_SESSION['trener_id'];$errors=[];$preview=null;$success=(string)($_SESSION['flash_success']??'');unset($_SESSION['flash_success']);
if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!csrf_verify((string)($_POST['csrf_token']??'')))$errors[]='Formulář vypršel. Obnovte stránku.';
    else try{$action=(string)($_POST['action']??'');
        if($action==='create'){memberFeePlanCreate($pdo,$actorId,['team_id'=>(int)$_POST['team_id'],'name'=>(string)$_POST['name'],'charge_title'=>(string)$_POST['charge_title'],'amount_minor'=>mfpAmount((string)$_POST['amount_czk']),'due_day'=>(int)$_POST['due_day'],'starts_on'=>(string)$_POST['starts_on'],'ends_on'=>(string)($_POST['ends_on']??'')],(string)$_POST['reason'],($_POST['confirmed']??'')==='1');$_SESSION['flash_success']='Měsíční plán byl založen.';header('Location: member_fee_plans_admin.php');exit;}
        if($action==='exclude'){memberFeePlanAddExclusion($pdo,(int)$_POST['plan_id'],(int)$_POST['sportovec_id'],$actorId,(string)$_POST['valid_from'],(string)($_POST['valid_to']??''),(string)$_POST['reason'],($_POST['confirmed']??'')==='1');$_SESSION['flash_success']='Výjimka z předpisu byla uložena.';header('Location: member_fee_plans_admin.php?plan_id='.(int)$_POST['plan_id']);exit;}
        if($action==='preview')$preview=memberFeePlanPreview($pdo,(int)$_POST['plan_id'],(string)$_POST['period']);
        elseif($action==='generate'){$result=memberFeePlanGenerate($pdo,(int)$_POST['plan_id'],(string)$_POST['period'],$actorId,(string)$_POST['reason'],(string)$_POST['preview_fingerprint'],($_POST['confirmed']??'')==='1');$_SESSION['flash_success']=$result['idempotent']?'Toto období už bylo vytvořeno; žádné duplicity nevznikly.':'Vytvořeno '.$result['generated_count'].' předpisů, přeskočeno '.$result['skipped_count'].'.';header('Location: member_fee_plans_admin.php?plan_id='.(int)$_POST['plan_id']);exit;}
    }catch(InvalidArgumentException|MemberFeePlanException|MemberChargeAdminException|ShopCheckoutException$exception){$errors[]=$exception->getMessage();}catch(Throwable$exception){error_log('member_fee_plans_admin.php: '.$exception->getMessage());$errors[]='Operace selhala bez částečného zápisu.';}
}
$plans=$pdo->query("SELECT p.*,t.name AS team_name FROM member_fee_plans p JOIN club_teams t ON t.id=p.team_id ORDER BY p.status='active' DESC,p.name,p.id")->fetchAll(PDO::FETCH_ASSOC);
$teams=$pdo->query("SELECT t.id,t.name,s.name AS season_name FROM club_teams t JOIN club_seasons s ON s.id=t.season_id WHERE t.status='active' AND s.status='active' ORDER BY s.starts_on DESC,t.name")->fetchAll(PDO::FETCH_ASSOC);
$selectedPlan=max(0,(int)($_GET['plan_id']??($preview['plan']['id']??0)));$members=[];$exclusions=[];
if($selectedPlan>0){$plan=memberFeePlanRow($pdo,$selectedPlan);if($plan){$membersStmt=$pdo->prepare("SELECT DISTINCT sp.id,sp.jmeno,sp.prijmeni FROM club_roster_members m JOIN sportovci sp ON sp.id=m.sportovec_id WHERE m.team_id=? AND m.status='active' ORDER BY sp.prijmeni,sp.jmeno");$membersStmt->execute([(int)$plan['team_id']]);$members=$membersStmt->fetchAll(PDO::FETCH_ASSOC);$exclusionStmt=$pdo->prepare('SELECT e.*,s.jmeno,s.prijmeni FROM member_fee_plan_exclusions e JOIN sportovci s ON s.id=e.sportovec_id WHERE e.plan_id=? ORDER BY e.valid_from DESC,e.id DESC');$exclusionStmt->execute([$selectedPlan]);$exclusions=$exclusionStmt->fetchAll(PDO::FETCH_ASSOC);}}
$currentPeriod=(new DateTimeImmutable('first day of this month'))->format('Y-m');$today=(new DateTimeImmutable('today'))->format('Y-m-d');
?>
<!doctype html><html lang="cs"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Plány členských příspěvků</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"></head><body class="bg-light"><?php require __DIR__.'/hlavicka.php';?>
<main class="container py-4" style="max-width:1250px"><div class="d-flex flex-wrap justify-content-between gap-2 mb-4"><div><h1 class="h3 mb-1">Plány členských příspěvků</h1><p class="text-muted mb-0">Měsíční běh vytvoří předpisy členům platné soupisky. Každý sportovec dostane stálý variabilní symbol pro trvalý příkaz; Fio páruje platbu s nejstarším neuhrazeným měsícem.</p></div><a class="btn btn-outline-secondary align-self-start" href="member_charges_admin.php">Jednotlivé předpisy</a></div>
<?php foreach($errors as$error):?><div class="alert alert-danger"><?=mfph($error)?></div><?php endforeach;?><?php if($success!==''):?><div class="alert alert-success"><?=mfph($success)?></div><?php endif;?>
<section class="card card-body border-0 shadow-sm mb-4"><h2 class="h5">Nový měsíční plán</h2><form method="post" class="row g-3"><?=csrf_field()?><input type="hidden" name="action" value="create"><div class="col-md-4"><label class="form-label">Soupiska</label><select class="form-select" name="team_id" required><option value="">Vyberte</option><?php foreach($teams as$team):?><option value="<?=(int)$team['id']?>"><?=mfph($team['season_name'].' · '.$team['name'])?></option><?php endforeach;?></select></div><div class="col-md-4"><label class="form-label">Název plánu</label><input class="form-control" name="name" required placeholder="Závodní oddíl – měsíční příspěvek"></div><div class="col-md-4"><label class="form-label">Text předpisu</label><input class="form-control" name="charge_title" required value="Měsíční členský příspěvek"></div><div class="col-md-2"><label class="form-label">Částka Kč</label><input class="form-control" name="amount_czk" inputmode="decimal" required></div><div class="col-md-2"><label class="form-label">Splatnost (den)</label><input class="form-control" type="number" name="due_day" min="1" max="28" value="15" required></div><div class="col-md-2"><label class="form-label">Platí od</label><input class="form-control" type="date" name="starts_on" value="<?=$today?>" required></div><div class="col-md-2"><label class="form-label">Platí do</label><input class="form-control" type="date" name="ends_on"></div><div class="col-md-4"><label class="form-label">Auditovaný důvod</label><input class="form-control" name="reason" value="Založení pravidelného měsíčního předpisu." required></div><div class="col-md-9 form-check ms-2"><input class="form-check-input" type="checkbox" id="mfp-create-confirm" name="confirmed" value="1" required><label class="form-check-label" for="mfp-create-confirm">Potvrzuji parametry plánu</label></div><div class="col-md-2 ms-auto d-grid"><button class="btn btn-primary">Založit plán</button></div></form></section>
<div class="row g-4"><div class="col-lg-5"><section class="card border-0 shadow-sm"><div class="card-header bg-white"><strong>Aktivní plány</strong></div><div class="list-group list-group-flush"><?php foreach($plans as$plan):?><a class="list-group-item list-group-item-action <?=$selectedPlan===(int)$plan['id']?'active':''?>" href="?plan_id=<?=(int)$plan['id']?>"><strong><?=mfph($plan['name'])?></strong><div class="small <?= $selectedPlan===(int)$plan['id']?'':'text-muted' ?>"><?=mfph($plan['team_name'])?> · <?=number_format((int)$plan['amount_minor']/100,2,',',' ')?> Kč · splatnost <?=$plan['due_day']?>.</div></a><?php endforeach;?><?php if($plans===[]):?><div class="list-group-item text-muted">Zatím není založen žádný plán.</div><?php endif;?></div></section></div>
<div class="col-lg-7"><?php if($selectedPlan>0):?><section class="card card-body border-0 shadow-sm mb-4"><h2 class="h5">Připravit období</h2><form method="post" class="row g-2 align-items-end"><?=csrf_field()?><input type="hidden" name="action" value="preview"><input type="hidden" name="plan_id" value="<?=$selectedPlan?>"><div class="col-8"><label class="form-label">Měsíc</label><input class="form-control" type="month" name="period" value="<?=mfph($preview['period']??$currentPeriod)?>" required></div><div class="col-4 d-grid"><button class="btn btn-outline-primary">Nejdříve náhled</button></div></form></section>
<section class="card card-body border-0 shadow-sm mb-4"><h2 class="h5">Výjimka pro člena</h2><form method="post" class="row g-2"><?=csrf_field()?><input type="hidden" name="action" value="exclude"><input type="hidden" name="plan_id" value="<?=$selectedPlan?>"><div class="col-md-6"><select class="form-select" name="sportovec_id" required><option value="">Vyberte člena</option><?php foreach($members as$member):?><option value="<?=(int)$member['id']?>"><?=mfph($member['prijmeni'].' '.$member['jmeno'])?></option><?php endforeach;?></select></div><div class="col-md-3"><input class="form-control" type="date" name="valid_from" value="<?=$today?>" required></div><div class="col-md-3"><input class="form-control" type="date" name="valid_to"></div><div class="col-md-8"><input class="form-control" name="reason" placeholder="Důvod výjimky" required></div><div class="col-md-2 form-check pt-2"><input class="form-check-input" type="checkbox" name="confirmed" value="1" id="mfp-exclude" required><label class="form-check-label" for="mfp-exclude">Potvrdit</label></div><div class="col-md-2 d-grid"><button class="btn btn-outline-danger">Uložit</button></div></form><?php if($exclusions!==[]):?><ul class="small mt-3 mb-0"><?php foreach($exclusions as$exclusion):?><li><?=mfph($exclusion['prijmeni'].' '.$exclusion['jmeno'].' · '.$exclusion['valid_from'].'–'.($exclusion['valid_to']?:'bez konce').' · '.$exclusion['reason'])?></li><?php endforeach;?></ul><?php endif;?></section><?php endif;?>
<?php if($preview):?><section class="card border-primary shadow-sm"><div class="card-header bg-primary text-white"><strong>Náhled <?=$preview['period']?></strong> · připraveno <?=$preview['ready_count']?> · přeskočeno <?=$preview['skipped_count']?></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Člen</th><th>Výsledek</th><th>Detail</th></tr></thead><tbody><?php foreach($preview['rows']as$row):?><tr><td><?=mfph($row['name'])?></td><td><code><?=mfph($row['result'])?></code></td><td><?=mfph($row['detail'])?></td></tr><?php endforeach;?></tbody></table></div><div class="card-body"><form method="post" class="row g-2"><?=csrf_field()?><input type="hidden" name="action" value="generate"><input type="hidden" name="plan_id" value="<?=(int)$preview['plan']['id']?>"><input type="hidden" name="period" value="<?=mfph($preview['period'])?>"><input type="hidden" name="preview_fingerprint" value="<?=mfph($preview['fingerprint'])?>"><div class="col-md-7"><label class="form-label">Auditovaný důvod</label><input class="form-control" name="reason" value="Vytvoření měsíčních předpisů podle potvrzeného náhledu." required></div><div class="col-md-3 form-check pt-4"><input class="form-check-input" type="checkbox" name="confirmed" value="1" id="mfp-generate" required><label class="form-check-label" for="mfp-generate">Vytvořit <?=$preview['ready_count']?> předpisů</label></div><div class="col-md-2 d-grid"><button class="btn btn-danger" <?=$preview['ready_count']<1?'disabled':''?>>Vytvořit</button></div></form></div></section><?php endif;?></div></div>
</main></body></html>
