<?php
declare(strict_types=1);
require_once __DIR__.'/includes/init.php';require_once __DIR__.'/csrf_helper.php';require_once __DIR__.'/includes/roster_message.php';
if(!isset($_SESSION['trener_id'])){header('Location: login.php');exit;}staffRequireActivePosition('registrar');
function rmh(mixed$value):string{return htmlspecialchars((string)$value,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
$actorId=(int)$_SESSION['trener_id'];$errors=[];$preview=null;$success=(string)($_SESSION['flash_success']??'');unset($_SESSION['flash_success']);
if($_SERVER['REQUEST_METHOD']==='POST'){if(!csrf_verify((string)($_POST['csrf_token']??'')))$errors[]='Formulář vypršel. Obnovte stránku.';else try{$action=(string)($_POST['action']??'');if($action==='preview')$preview=rosterMessagePreview($pdo,(int)$_POST['team_id'],(string)$_POST['subject'],(string)$_POST['body']);elseif($action==='enqueue'){$result=rosterMessageEnqueue($pdo,(int)$_POST['team_id'],(string)$_POST['subject'],(string)$_POST['body'],(string)$_POST['preview_fingerprint'],$actorId,(string)$_POST['reason'],($_POST['confirmed']??'')==='1');$_SESSION['flash_success']='Zpráva byla zařazena pro '.$result['recipient_count'].' ověřených účtů.';header('Location: roster_messages_admin.php');exit;}else throw new InvalidArgumentException('Neznámá akce.');}catch(InvalidArgumentException|RosterMessageException$exception){$errors[]=$exception->getMessage();}catch(Throwable$exception){error_log('roster_messages_admin.php: '.$exception->getMessage());$errors[]='Operace selhala bez částečného zápisu.';}}
$teams=$pdo->query("SELECT t.id,t.name,s.name AS season_name,s.starts_on FROM club_teams t JOIN club_seasons s ON s.id=t.season_id WHERE t.status='active' AND s.status='active' ORDER BY s.starts_on DESC,t.name")->fetchAll(PDO::FETCH_ASSOC);$messages=$pdo->query("SELECT m.*,t.name AS team_name,(SELECT COUNT(*) FROM roster_message_recipients r WHERE r.message_id=m.id AND r.status='sent') AS sent_count,(SELECT COUNT(*) FROM roster_message_recipients r WHERE r.message_id=m.id AND r.status='failed') AS failed_count FROM roster_messages m JOIN club_teams t ON t.id=m.team_id ORDER BY m.id DESC LIMIT 100")->fetchAll(PDO::FETCH_ASSOC);
?>
<!doctype html><html lang="cs"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Komunikace se soupiskami</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"></head><body class="bg-light"><?php require __DIR__.'/hlavicka.php';?><main class="container py-4" style="max-width:1150px"><div class="d-flex flex-wrap justify-content-between gap-2 mb-4"><div><h1 class="h3 mb-1">Komunikace se soupiskami</h1><p class="text-muted mb-0">Příjemci se načtou z platné soupisky a ověřených vlastních nebo rodičovských účtů. Náhled nic neodesílá.</p></div><a class="btn btn-outline-secondary align-self-start" href="kis_rosters_admin.php">Týmy a soupisky</a></div>
<?php foreach($errors as$error):?><div class="alert alert-danger"><?=rmh($error)?></div><?php endforeach;?><?php if($success!==''):?><div class="alert alert-success"><?=rmh($success)?></div><?php endif;?>
<section class="card card-body border-0 shadow-sm mb-4"><h2 class="h5">Nová zpráva</h2><form method="post" class="row g-3"><?=csrf_field()?><input type="hidden" name="action" value="preview"><div class="col-md-5"><label class="form-label">Soupiska</label><select class="form-select" name="team_id" required><option value="">Vyberte</option><?php foreach($teams as$team):?><option value="<?=(int)$team['id']?>" <?=isset($preview)&&$preview&&(int)$preview['team']['id']===(int)$team['id']?'selected':''?>><?=rmh($team['season_name'].' · '.$team['name'])?></option><?php endforeach;?></select></div><div class="col-md-7"><label class="form-label">Předmět</label><input class="form-control" name="subject" maxlength="255" value="<?=rmh($preview['subject']??'')?>" required></div><div class="col-12"><label class="form-label">Text zprávy</label><textarea class="form-control" name="body" rows="7" maxlength="10000" required><?=rmh($preview['body']??'')?></textarea></div><div class="col-12 d-grid d-md-flex justify-content-md-end"><button class="btn btn-outline-primary">Zobrazit příjemce a obsah</button></div></form></section>
<?php if($preview):?><section class="card border-primary shadow-sm mb-4"><div class="card-header bg-primary text-white"><strong>Náhled: <?=rmh($preview['team']['name'])?></strong> · <?=count($preview['recipients'])?> účtů</div><div class="card-body"><h3 class="h6"><?=rmh($preview['subject'])?></h3><div class="border rounded bg-light p-3 mb-3" style="white-space:pre-wrap"><?=rmh($preview['body'])?></div><details class="mb-3"><summary>Příjemci (<?=count($preview['recipients'])?>)</summary><ul class="small mt-2"><?php foreach($preview['recipients']as$recipient):?><li><?=rmh($recipient['name'].' · '.$recipient['email'])?></li><?php endforeach;?></ul></details><form method="post" class="row g-2"><?=csrf_field()?><input type="hidden" name="action" value="enqueue"><input type="hidden" name="team_id" value="<?=(int)$preview['team']['id']?>"><input type="hidden" name="subject" value="<?=rmh($preview['subject'])?>"><input type="hidden" name="body" value="<?=rmh($preview['body'])?>"><input type="hidden" name="preview_fingerprint" value="<?=rmh($preview['fingerprint'])?>"><div class="col-md-7"><label class="form-label">Auditovaný důvod</label><input class="form-control" name="reason" value="Provozní komunikace členům vybrané soupisky." required></div><div class="col-md-3 form-check pt-4"><input class="form-check-input" type="checkbox" name="confirmed" value="1" id="roster-message-confirm" required><label class="form-check-label" for="roster-message-confirm">Zařadit <?=count($preview['recipients'])?> zpráv</label></div><div class="col-md-2 d-grid"><button class="btn btn-danger" <?=count($preview['recipients'])<1?'disabled':''?>>Zařadit</button></div></form></div></section><?php endif;?>
<section class="card border-0 shadow-sm"><div class="card-header bg-white"><strong>Historie fronty</strong></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Vytvořeno</th><th>Soupiska a předmět</th><th>Stav</th><th>Doručení</th></tr></thead><tbody><?php foreach($messages as$message):?><tr><td><?=rmh($message['created_at'])?></td><td><strong><?=rmh($message['team_name'])?></strong><div><?=rmh($message['subject_plain'])?></div></td><td><span class="badge text-bg-<?=in_array($message['status'],['sent'],true)?'success':(in_array($message['status'],['failed','partial'],true)?'danger':'warning')?>"><?=rmh($message['status'])?></span></td><td><?= (int)$message['sent_count']?> / <?=(int)$message['recipient_count']?> odesláno<?php if((int)$message['failed_count']>0):?> · <span class="text-danger"><?=(int)$message['failed_count']?> selhalo</span><?php endif;?></td></tr><?php endforeach;?><?php if($messages===[]):?><tr><td colspan="4" class="text-muted text-center py-4">Zatím nebyla zařazena žádná zpráva.</td></tr><?php endif;?></tbody></table></div></section>
</main></body></html>
